<a href="https://colab.research.google.com/github/npappin-wsu/BroadbandDataQuickstart/blob/main/Broadband_Data_Quickstart_Hour_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/npappin-wsu/BroadbandDataQuickstart.git data

Cloning into 'data'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 12 (delta 2), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (12/12), 599.17 KiB | 1.22 MiB/s, done.
Resolving deltas: 100% (2/2), done.

In [2]:
!pip install -r data/requirements.txt

Collecting bdcdata (from -r data/requirements.txt (line 1))
  Downloading bdcdata-0.0.9-py3-none-any.whl.metadata (900 bytes)
Requirement already satisfied: pandas>=2 in /usr/local/lib/python3.12/dist-packages (from bdcdata->-r data/requirements.txt (line 1)) (2.2.2)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (from bdcdata->-r data/requirements.txt (line 1)) (18.1.0)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (from bdcdata->-r data/requirements.txt (line 1)) (1.1.1)
Collecting requests-ratelimiter (from bdcdata->-r data/requirements.txt (line 1))
  Downloading requests_ratelimiter-0.7.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=2->bdcdata->-r data/requirements.txt (line 1)) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2->bdcdata->-r data/requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2->bdcdata->-r data/requirements.txt (line 1)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2->bdcdata->-r data/requirements.txt (line 1)) (2025.2)
Collecting pyrate-limiter<3.0 (from requests-ratelimiter->bdcdata->-r data/requirements.txt (line 1))
  Downloading pyrate_limiter-2.10.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.12/dist-packages (from requests-ratelimiter->bdcdata->-r data/requirements.txt (line 1)) (2.32.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2->bdcdata->-r data/requirements.txt (line 1)) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->requests-ratelimiter->bdcdata->-r data/requirements.txt (line 1)) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->requests-ratelimiter->bdcdata->-r data/requirements.txt (line 1)) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->requests-ratelimiter->bdcdata->-r data/requirements.txt (line 1)) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->requests-ratelimiter->bdcdata->-r data/requirements.txt (line 1)) (2025.8.3)
Downloading bdcdata-0.0.9-py3-none-any.whl (5.9 kB)
Downloading requests_ratelimiter-0.7.0-py3-none-any.whl (9.3 kB)
Downloading pyrate_limiter-2.10.0-py3-none-any.whl (16 kB)
Installing collected packages: pyrate-limiter, requests-ratelimiter, bdcdata
Successfully installed bdcdata-0.0.9 pyrate-limiter-2.10.0 requests-ratelimiter-0.7.0

In [14]:
import os, pathlib
from google.colab import userdata
import pandas as pd
os.environ["BDC_USERNAME"] = userdata.get('bdc_email')
os.environ["BDC_API_KEY"] = userdata.get('bdc_hash')

In [4]:
import bdcdata

{'User-Agent': 'python-bdc', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'hash_value': '2y/1NvvejDWWuZt4vXrkL9LQ4QNeprc1qPzW8w8Zvz0=', 'username': 'nick.pappin@wsu.edu'}
DEBUG:bdcdata:{'User-Agent': 'python-bdc', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'hash_value': '2y/1NvvejDWWuZt4vXrkL9LQ4QNeprc1qPzW8w8Zvz0=', 'username': 'nick.pappin@wsu.edu'}
Session created.
INFO:bdcdata:Session created.
Collecting metadata...
INFO:bdcdata:Collecting metadata...
{'data': [{'data_type': 'availability', 'as_of_date': '2022-06-30'}, {'data_type': 'availability', 'as_of_date': '2022-12-31'}, {'data_type': 'availability', 'as_of_date': '2023-06-30'}, {'data_type': 'availability', 'as_of_date': '2023-12-31'}, {'data_type': 'availability', 'as_of_date': '2024-06-30'}, {'data_type': 'availability', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2022-11-30'}, {'data_type': 'challenge', 'as_of_date': '2022-12-31'}, {'data_type': 'challenge', 'as_of_date': '2023-01-31'}, {'data_type': 'challenge', 'as_of_date': '2023-02-28'}, {'data_type': 'challenge', 'as_of_date': '2023-03-31'}, {'data_type': 'challenge', 'as_of_date': '2023-04-30'}, {'data_type': 'challenge', 'as_of_date': '2023-05-31'}, {'data_type': 'challenge', 'as_of_date': '2023-06-30'}, {'data_type': 'challenge', 'as_of_date': '2023-07-31'}, {'data_type': 'challenge', 'as_of_date': '2023-08-31'}, {'data_type': 'challenge', 'as_of_date': '2023-09-30'}, {'data_type': 'challenge', 'as_of_date': '2023-10-31'}, {'data_type': 'challenge', 'as_of_date': '2023-11-30'}, {'data_type': 'challenge', 'as_of_date': '2023-12-31'}, {'data_type': 'challenge', 'as_of_date': '2024-01-31'}, {'data_type': 'challenge', 'as_of_date': '2024-02-29'}, {'data_type': 'challenge', 'as_of_date': '2024-03-31'}, {'data_type': 'challenge', 'as_of_date': '2024-04-30'}, {'data_type': 'challenge', 'as_of_date': '2024-05-31'}, {'data_type': 'challenge', 'as_of_date': '2024-06-30'}, {'data_type': 'challenge', 'as_of_date': '2024-07-31'}, {'data_type': 'challenge', 'as_of_date': '2024-08-31'}, {'data_type': 'challenge', 'as_of_date': '2024-09-30'}, {'data_type': 'challenge', 'as_of_date': '2024-10-31'}, {'data_type': 'challenge', 'as_of_date': '2024-11-30'}, {'data_type': 'challenge', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2025-01-31'}, {'data_type': 'challenge', 'as_of_date': '2025-02-28'}, {'data_type': 'challenge', 'as_of_date': '2025-03-31'}, {'data_type': 'challenge', 'as_of_date': '2025-04-30'}, {'data_type': 'challenge', 'as_of_date': '2025-05-31'}, {'data_type': 'challenge', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2025-07-31'}, {'data_type': 'challenge', 'as_of_date': '2025-08-31'}], 'result_count': 40, 'status_code': 200, 'message': None, 'status': 'successful', 'request_date': '2025-09-03T19:48:20.037Z'}
DEBUG:bdcdata:{'data': [{'data_type': 'availability', 'as_of_date': '2022-06-30'}, {'data_type': 'availability', 'as_of_date': '2022-12-31'}, {'data_type': 'availability', 'as_of_date': '2023-06-30'}, {'data_type': 'availability', 'as_of_date': '2023-12-31'}, {'data_type': 'availability', 'as_of_date': '2024-06-30'}, {'data_type': 'availability', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2022-11-30'}, {'data_type': 'challenge', 'as_of_date': '2022-12-31'}, {'data_type': 'challenge', 'as_of_date': '2023-01-31'}, {'data_type': 'challenge', 'as_of_date': '2023-02-28'}, {'data_type': 'challenge', 'as_of_date': '2023-03-31'}, {'data_type': 'challenge', 'as_of_date': '2023-04-30'}, {'data_type': 'challenge', 'as_of_date': '2023-05-31'}, {'data_type': 'challenge', 'as_of_date': '2023-06-30'}, {'data_type': 'challenge', 'as_of_date': '2023-07-31'}, {'data_type': 'challenge', 'as_of_date': '2023-08-31'}, {'data_type': 'challenge', 'as_of_date': '2023-09-30'}, {'data_type': 'challenge', 'as_of_date': '2023-10-31'}, {'data_type': 'challenge', 'as_of_date': '2023-11-30'}, {'data_type': 'challenge', 'as_of_date': '2023-12-31'}, {'data_type': 'challenge', 'as_of_date': '2024-01-31'}, {'data_type': 'challenge', 'as_of_date': '2024-02-29'}, {'data_type': 'challenge', 'as_of_date': '2024-03-31'}, {'data_type': 'challenge', 'as_of_date': '2024-04-30'}, {'data_type': 'challenge', 'as_of_date': '2024-05-31'}, {'data_type': 'challenge', 'as_of_date': '2024-06-30'}, {'data_type': 'challenge', 'as_of_date': '2024-07-31'}, {'data_type': 'challenge', 'as_of_date': '2024-08-31'}, {'data_type': 'challenge', 'as_of_date': '2024-09-30'}, {'data_type': 'challenge', 'as_of_date': '2024-10-31'}, {'data_type': 'challenge', 'as_of_date': '2024-11-30'}, {'data_type': 'challenge', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2025-01-31'}, {'data_type': 'challenge', 'as_of_date': '2025-02-28'}, {'data_type': 'challenge', 'as_of_date': '2025-03-31'}, {'data_type': 'challenge', 'as_of_date': '2025-04-30'}, {'data_type': 'challenge', 'as_of_date': '2025-05-31'}, {'data_type': 'challenge', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2025-07-31'}, {'data_type': 'challenge', 'as_of_date': '2025-08-31'}], 'result_count': 40, 'status_code': 200, 'message': None, 'status': 'successful', 'request_date': '2025-09-03T19:48:20.037Z'}
{'data': [{'data_type': 'availability', 'as_of_date': '2022-06-30'}, {'data_type': 'availability', 'as_of_date': '2022-12-31'}, {'data_type': 'availability', 'as_of_date': '2023-06-30'}, {'data_type': 'availability', 'as_of_date': '2023-12-31'}, {'data_type': 'availability', 'as_of_date': '2024-06-30'}, {'data_type': 'availability', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2022-11-30'}, {'data_type': 'challenge', 'as_of_date': '2022-12-31'}, {'data_type': 'challenge', 'as_of_date': '2023-01-31'}, {'data_type': 'challenge', 'as_of_date': '2023-02-28'}, {'data_type': 'challenge', 'as_of_date': '2023-03-31'}, {'data_type': 'challenge', 'as_of_date': '2023-04-30'}, {'data_type': 'challenge', 'as_of_date': '2023-05-31'}, {'data_type': 'challenge', 'as_of_date': '2023-06-30'}, {'data_type': 'challenge', 'as_of_date': '2023-07-31'}, {'data_type': 'challenge', 'as_of_date': '2023-08-31'}, {'data_type': 'challenge', 'as_of_date': '2023-09-30'}, {'data_type': 'challenge', 'as_of_date': '2023-10-31'}, {'data_type': 'challenge', 'as_of_date': '2023-11-30'}, {'data_type': 'challenge', 'as_of_date': '2023-12-31'}, {'data_type': 'challenge', 'as_of_date': '2024-01-31'}, {'data_type': 'challenge', 'as_of_date': '2024-02-29'}, {'data_type': 'challenge', 'as_of_date': '2024-03-31'}, {'data_type': 'challenge', 'as_of_date': '2024-04-30'}, {'data_type': 'challenge', 'as_of_date': '2024-05-31'}, {'data_type': 'challenge', 'as_of_date': '2024-06-30'}, {'data_type': 'challenge', 'as_of_date': '2024-07-31'}, {'data_type': 'challenge', 'as_of_date': '2024-08-31'}, {'data_type': 'challenge', 'as_of_date': '2024-09-30'}, {'data_type': 'challenge', 'as_of_date': '2024-10-31'}, {'data_type': 'challenge', 'as_of_date': '2024-11-30'}, {'data_type': 'challenge', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2025-01-31'}, {'data_type': 'challenge', 'as_of_date': '2025-02-28'}, {'data_type': 'challenge', 'as_of_date': '2025-03-31'}, {'data_type': 'challenge', 'as_of_date': '2025-04-30'}, {'data_type': 'challenge', 'as_of_date': '2025-05-31'}, {'data_type': 'challenge', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2025-07-31'}, {'data_type': 'challenge', 'as_of_date': '2025-08-31'}], 'result_count': 40, 'status_code': 200, 'message': None, 'status': 'successful', 'request_date': '2025-09-03T19:48:20.037Z'}
INFO:bdcdata:{'data': [{'data_type': 'availability', 'as_of_date': '2022-06-30'}, {'data_type': 'availability', 'as_of_date': '2022-12-31'}, {'data_type': 'availability', 'as_of_date': '2023-06-30'}, {'data_type': 'availability', 'as_of_date': '2023-12-31'}, {'data_type': 'availability', 'as_of_date': '2024-06-30'}, {'data_type': 'availability', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2022-11-30'}, {'data_type': 'challenge', 'as_of_date': '2022-12-31'}, {'data_type': 'challenge', 'as_of_date': '2023-01-31'}, {'data_type': 'challenge', 'as_of_date': '2023-02-28'}, {'data_type': 'challenge', 'as_of_date': '2023-03-31'}, {'data_type': 'challenge', 'as_of_date': '2023-04-30'}, {'data_type': 'challenge', 'as_of_date': '2023-05-31'}, {'data_type': 'challenge', 'as_of_date': '2023-06-30'}, {'data_type': 'challenge', 'as_of_date': '2023-07-31'}, {'data_type': 'challenge', 'as_of_date': '2023-08-31'}, {'data_type': 'challenge', 'as_of_date': '2023-09-30'}, {'data_type': 'challenge', 'as_of_date': '2023-10-31'}, {'data_type': 'challenge', 'as_of_date': '2023-11-30'}, {'data_type': 'challenge', 'as_of_date': '2023-12-31'}, {'data_type': 'challenge', 'as_of_date': '2024-01-31'}, {'data_type': 'challenge', 'as_of_date': '2024-02-29'}, {'data_type': 'challenge', 'as_of_date': '2024-03-31'}, {'data_type': 'challenge', 'as_of_date': '2024-04-30'}, {'data_type': 'challenge', 'as_of_date': '2024-05-31'}, {'data_type': 'challenge', 'as_of_date': '2024-06-30'}, {'data_type': 'challenge', 'as_of_date': '2024-07-31'}, {'data_type': 'challenge', 'as_of_date': '2024-08-31'}, {'data_type': 'challenge', 'as_of_date': '2024-09-30'}, {'data_type': 'challenge', 'as_of_date': '2024-10-31'}, {'data_type': 'challenge', 'as_of_date': '2024-11-30'}, {'data_type': 'challenge', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2025-01-31'}, {'data_type': 'challenge', 'as_of_date': '2025-02-28'}, {'data_type': 'challenge', 'as_of_date': '2025-03-31'}, {'data_type': 'challenge', 'as_of_date': '2025-04-30'}, {'data_type': 'challenge', 'as_of_date': '2025-05-31'}, {'data_type': 'challenge', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2025-07-31'}, {'data_type': 'challenge', 'as_of_date': '2025-08-31'}], 'result_count': 40, 'status_code': 200, 'message': None, 'status': 'successful', 'request_date': '2025-09-03T19:48:20.037Z'}
[{'data_type': 'availability', 'as_of_date': '2022-06-30'}, {'data_type': 'availability', 'as_of_date': '2022-12-31'}, {'data_type': 'availability', 'as_of_date': '2023-06-30'}, {'data_type': 'availability', 'as_of_date': '2023-12-31'}, {'data_type': 'availability', 'as_of_date': '2024-06-30'}, {'data_type': 'availability', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2022-11-30'}, {'data_type': 'challenge', 'as_of_date': '2022-12-31'}, {'data_type': 'challenge', 'as_of_date': '2023-01-31'}, {'data_type': 'challenge', 'as_of_date': '2023-02-28'}, {'data_type': 'challenge', 'as_of_date': '2023-03-31'}, {'data_type': 'challenge', 'as_of_date': '2023-04-30'}, {'data_type': 'challenge', 'as_of_date': '2023-05-31'}, {'data_type': 'challenge', 'as_of_date': '2023-06-30'}, {'data_type': 'challenge', 'as_of_date': '2023-07-31'}, {'data_type': 'challenge', 'as_of_date': '2023-08-31'}, {'data_type': 'challenge', 'as_of_date': '2023-09-30'}, {'data_type': 'challenge', 'as_of_date': '2023-10-31'}, {'data_type': 'challenge', 'as_of_date': '2023-11-30'}, {'data_type': 'challenge', 'as_of_date': '2023-12-31'}, {'data_type': 'challenge', 'as_of_date': '2024-01-31'}, {'data_type': 'challenge', 'as_of_date': '2024-02-29'}, {'data_type': 'challenge', 'as_of_date': '2024-03-31'}, {'data_type': 'challenge', 'as_of_date': '2024-04-30'}, {'data_type': 'challenge', 'as_of_date': '2024-05-31'}, {'data_type': 'challenge', 'as_of_date': '2024-06-30'}, {'data_type': 'challenge', 'as_of_date': '2024-07-31'}, {'data_type': 'challenge', 'as_of_date': '2024-08-31'}, {'data_type': 'challenge', 'as_of_date': '2024-09-30'}, {'data_type': 'challenge', 'as_of_date': '2024-10-31'}, {'data_type': 'challenge', 'as_of_date': '2024-11-30'}, {'data_type': 'challenge', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2025-01-31'}, {'data_type': 'challenge', 'as_of_date': '2025-02-28'}, {'data_type': 'challenge', 'as_of_date': '2025-03-31'}, {'data_type': 'challenge', 'as_of_date': '2025-04-30'}, {'data_type': 'challenge', 'as_of_date': '2025-05-31'}, {'data_type': 'challenge', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2025-07-31'}, {'data_type': 'challenge', 'as_of_date': '2025-08-31'}]
DEBUG:bdcdata:[{'data_type': 'availability', 'as_of_date': '2022-06-30'}, {'data_type': 'availability', 'as_of_date': '2022-12-31'}, {'data_type': 'availability', 'as_of_date': '2023-06-30'}, {'data_type': 'availability', 'as_of_date': '2023-12-31'}, {'data_type': 'availability', 'as_of_date': '2024-06-30'}, {'data_type': 'availability', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2022-11-30'}, {'data_type': 'challenge', 'as_of_date': '2022-12-31'}, {'data_type': 'challenge', 'as_of_date': '2023-01-31'}, {'data_type': 'challenge', 'as_of_date': '2023-02-28'}, {'data_type': 'challenge', 'as_of_date': '2023-03-31'}, {'data_type': 'challenge', 'as_of_date': '2023-04-30'}, {'data_type': 'challenge', 'as_of_date': '2023-05-31'}, {'data_type': 'challenge', 'as_of_date': '2023-06-30'}, {'data_type': 'challenge', 'as_of_date': '2023-07-31'}, {'data_type': 'challenge', 'as_of_date': '2023-08-31'}, {'data_type': 'challenge', 'as_of_date': '2023-09-30'}, {'data_type': 'challenge', 'as_of_date': '2023-10-31'}, {'data_type': 'challenge', 'as_of_date': '2023-11-30'}, {'data_type': 'challenge', 'as_of_date': '2023-12-31'}, {'data_type': 'challenge', 'as_of_date': '2024-01-31'}, {'data_type': 'challenge', 'as_of_date': '2024-02-29'}, {'data_type': 'challenge', 'as_of_date': '2024-03-31'}, {'data_type': 'challenge', 'as_of_date': '2024-04-30'}, {'data_type': 'challenge', 'as_of_date': '2024-05-31'}, {'data_type': 'challenge', 'as_of_date': '2024-06-30'}, {'data_type': 'challenge', 'as_of_date': '2024-07-31'}, {'data_type': 'challenge', 'as_of_date': '2024-08-31'}, {'data_type': 'challenge', 'as_of_date': '2024-09-30'}, {'data_type': 'challenge', 'as_of_date': '2024-10-31'}, {'data_type': 'challenge', 'as_of_date': '2024-11-30'}, {'data_type': 'challenge', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2025-01-31'}, {'data_type': 'challenge', 'as_of_date': '2025-02-28'}, {'data_type': 'challenge', 'as_of_date': '2025-03-31'}, {'data_type': 'challenge', 'as_of_date': '2025-04-30'}, {'data_type': 'challenge', 'as_of_date': '2025-05-31'}, {'data_type': 'challenge', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2025-07-31'}, {'data_type': 'challenge', 'as_of_date': '2025-08-31'}]
Metadata collected.
INFO:bdcdata:Metadata collected.
Data type: availability
DEBUG:bdcdata:Data type: availability
{'data_type': 'availability', 'as_of_date': '2022-06-30'}
DEBUG:bdcdata:{'data_type': 'availability', 'as_of_date': '2022-06-30'}
Data type: availability
DEBUG:bdcdata:Data type: availability
{'data_type': 'availability', 'as_of_date': '2022-12-31'}
DEBUG:bdcdata:{'data_type': 'availability', 'as_of_date': '2022-12-31'}
Data type: availability
DEBUG:bdcdata:Data type: availability
{'data_type': 'availability', 'as_of_date': '2023-06-30'}
DEBUG:bdcdata:{'data_type': 'availability', 'as_of_date': '2023-06-30'}
Data type: availability
DEBUG:bdcdata:Data type: availability
{'data_type': 'availability', 'as_of_date': '2023-12-31'}
DEBUG:bdcdata:{'data_type': 'availability', 'as_of_date': '2023-12-31'}
Data type: availability
DEBUG:bdcdata:Data type: availability
{'data_type': 'availability', 'as_of_date': '2024-06-30'}
DEBUG:bdcdata:{'data_type': 'availability', 'as_of_date': '2024-06-30'}
Data type: availability
DEBUG:bdcdata:Data type: availability
{'data_type': 'availability', 'as_of_date': '2024-12-31'}
DEBUG:bdcdata:{'data_type': 'availability', 'as_of_date': '2024-12-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2022-11-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2022-11-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2022-12-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2022-12-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-01-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-01-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-02-28'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-02-28'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-03-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-03-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-04-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-04-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-05-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-05-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-06-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-06-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-07-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-07-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-08-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-08-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-09-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-09-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-10-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-10-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-11-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-11-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-12-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-12-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-01-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-01-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-02-29'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-02-29'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-03-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-03-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-04-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-04-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-05-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-05-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-06-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-06-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-07-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-07-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-08-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-08-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-09-30'}

In [6]:
waData = bdcdata.availability.fixed(states=[53], technology='fixed', release=['2024-12-31'], cache=True)

Collecting availability...
INFO:bdcdata:Collecting availability...
State: [53]
DEBUG:bdcdata:State: [53]
Technology: fixed
DEBUG:bdcdata:Technology: fixed
Release: ['2024-12-31']
DEBUG:bdcdata:Release: ['2024-12-31']
State: Washington({'file_id': 1202803, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '10', 'technology_code_desc': 'Copper', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_Copper_fixed_broadband_D24_19aug2025', 'record_count': '1211997'})), Technology: 10, Release: 2024-12-31
DEBUG:bdcdata:State: Washington({'file_id': 1202803, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '10', 'technology_code_desc': 'Copper', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_Copper_fixed_broadband_D24_19aug2025', 'record_count': '1211997'})), Technology: 10, Release: 2024-12-31
Cache hit!
DEBUG:bdcdata:Cache hit!
State: Washington({'file_id': 1202857, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '40', 'technology_code_desc': 'Cable', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_Cable_fixed_broadband_D24_19aug2025', 'record_count': '2296181'})), Technology: 40, Release: 2024-12-31
DEBUG:bdcdata:State: Washington({'file_id': 1202857, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '40', 'technology_code_desc': 'Cable', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_Cable_fixed_broadband_D24_19aug2025', 'record_count': '2296181'})), Technology: 40, Release: 2024-12-31
Cache hit!
DEBUG:bdcdata:Cache hit!
State: Washington({'file_id': 1202913, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '50', 'technology_code_desc': 'Fiber to the Premises', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_FibertothePremises_fixed_broadband_D24_19aug2025', 'record_count': '1207365'})), Technology: 50, Release: 2024-12-31
DEBUG:bdcdata:State: Washington({'file_id': 1202913, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '50', 'technology_code_desc': 'Fiber to the Premises', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_FibertothePremises_fixed_broadband_D24_19aug2025', 'record_count': '1207365'})), Technology: 50, Release: 2024-12-31
Cache hit!
DEBUG:bdcdata:Cache hit!
State: Washington({'file_id': 1202969, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '60', 'technology_code_desc': 'GSO Satellite', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_GSOSatellite_fixed_broadband_D24_19aug2025', 'record_count': '7707217'})), Technology: 60, Release: 2024-12-31
DEBUG:bdcdata:State: Washington({'file_id': 1202969, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '60', 'technology_code_desc': 'GSO Satellite', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_GSOSatellite_fixed_broadband_D24_19aug2025', 'record_count': '7707217'})), Technology: 60, Release: 2024-12-31
Cache hit!
DEBUG:bdcdata:Cache hit!
State: Washington({'file_id': 1203022, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '61', 'technology_code_desc': 'NGSO Satellite', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_NGSOSatellite_fixed_broadband_D24_19aug2025', 'record_count': '2565799'})), Technology: 61, Release: 2024-12-31
DEBUG:bdcdata:State: Washington({'file_id': 1203022, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '61', 'technology_code_desc': 'NGSO Satellite', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_NGSOSatellite_fixed_broadband_D24_19aug2025', 'record_count': '2565799'})), Technology: 61, Release: 2024-12-31
Cache hit!
DEBUG:bdcdata:Cache hit!
State: Washington({'file_id': 1203077, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '70', 'technology_code_desc': 'Unlicensed Fixed Wireless', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_UnlicensedFixedWireless_fixed_broadband_D24_19aug2025', 'record_count': '1308505'})), Technology: 70, Release: 2024-12-31
DEBUG:bdcdata:State: Washington({'file_id': 1203077, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '70', 'technology_code_desc': 'Unlicensed Fixed Wireless', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_UnlicensedFixedWireless_fixed_broadband_D24_19aug2025', 'record_count': '1308505'})), Technology: 70, Release: 2024-12-31
Cache hit!
DEBUG:bdcdata:Cache hit!
State: Washington({'file_id': 1203132, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '71', 'technology_code_desc': 'Licensed Fixed Wireless', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_LicensedFixedWireless_fixed_broadband_D24_19aug2025', 'record_count': '3607054'})), Technology: 71, Release: 2024-12-31
DEBUG:bdcdata:State: Washington({'file_id': 1203132, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '71', 'technology_code_desc': 'Licensed Fixed Wireless', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_LicensedFixedWireless_fixed_broadband_D24_19aug2025', 'record_count': '3607054'})), Technology: 71, Release: 2024-12-31
State: Washington({'file_id': 1203182, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '72', 'technology_code_desc': 'LBR Fixed Wireless', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_LBRFixedWireless_fixed_broadband_D24_19aug2025', 'record_count': '170852'})), Technology: 72, Release: 2024-12-31
DEBUG:bdcdata:State: Washington({'file_id': 1203182, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '72', 'technology_code_desc': 'LBR Fixed Wireless', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_LBRFixedWireless_fixed_broadband_D24_19aug2025', 'record_count': '170852'})), Technology: 72, Release: 2024-12-31
State: ['53'], Technology: ['0', '10', '40', '50', '60', '61', '70', '71', '72'], Release: ['2024-12-31']
DEBUG:bdcdata:State: ['53'], Technology: ['0', '10', '40', '50', '60', '61', '70', '71', '72'], Release: ['2024-12-31']

In [7]:
waData

,frn,provider_id,brand_name,location_id,technology,max_advertised_download_speed,max_advertised_upload_speed,low_latency,business_residential_code,state_usps,block_geoid,h3_res8_id
0,0024000473,370071,Native Network Inc,1121308022,10,1000,1000,True,X,WA,530179504004020,8828d681a1fffff
1,0024000473,370071,Native Network Inc,1121309093,10,1000,1000,True,X,WA,530179503003009,8828d68133fffff
2,0024000473,370071,Native Network Inc,1121313485,10,1000,1000,True,X,WA,530179508002009,8828d6811bfffff
3,0024000473,370071,Native Network Inc,1121318023,10,1000,1000,True,X,WA,530179508003045,8828d68025fffff
4,0024000473,370071,Native Network Inc,1121319492,10,1000,1000,True,X,WA,530179505002001,8828d68189fffff
...,...,...,...,...,...,...,...,...,...,...,...,...
20074965,0026541029,470122,Advanced High Speed Internet,1305974388,72,100,30,True,X,WA,530779400023117,8828899547fffff
20074966,0026541029,470122,Advanced High Speed Internet,1305982096,72,100,30,True,X,WA,530770029004023,882889a1d1fffff
20074967,0026541029,470122,Advanced High Speed Internet,1305982516,72,100,30,True,X,WA,530770028011007,882889a219fffff
20074968,0026541029,470122,Advanced High Speed Internet,1305995631,72,100,30,True,X,WA,530770017012034,8828898c95fffff
20074969,0026541029,470122,Advanced High Speed Internet,1312148498,72,100,30,True,X,WA,530050118023028,88288d6f27fffff

In [11]:
locationLookup = waData[['location_id', 'block_geoid', 'h3_res8_id']].drop_duplicates(ignore_index=True)

In [12]:
locationLookup

         location_id      block_geoid       h3_res8_id
0         1121308022  530179504004020  8828d681a1fffff
1         1121309093  530179503003009  8828d68133fffff
2         1121313485  530179508002009  8828d6811bfffff
3         1121318023  530179508003045  8828d68025fffff
4         1121319492  530179505002001  8828d68189fffff
...              ...              ...              ...
2566303   1296414256  530459613002019  8828d594e3fffff
2566304   1305974388  530779400023117  8828899547fffff
2566305   1305995631  530770017012034  8828898c95fffff
2566306   1310144322  530730103011029  8828d169edfffff
2566307   1349409498  530110405043001  8828f07365fffff

[2566308 rows x 3 columns]

In [15]:
fpLocations = pd.read_csv(pathlib.Path('data', 'fp_locations.csv'))

In [21]:
fpLocations[['location_id', 'technology']].merge(locationLookup, how='left', on='location_id')

        location_id  technology      block_geoid       h3_res8_id
0        1024099225          61  530019501001104  88288b1169fffff
1        1024099256          61  530019503011093  8828882d85fffff
2        1024099803          61  530019501001244  88288a2621fffff
3        1024099831          61  530019501001158  88288bc603fffff
4        1024099838          61  530019502002050  88288b8f5bfffff
...             ...         ...              ...              ...
165968   1414834970          71  530379753003007  8828892c1bfffff
165969   1414834977          71  530379753001078  88288921a9fffff
165970   1414835005          71  530379753001085  8828892033fffff
165971   1414835015          50  530379753001116  8828892a1bfffff
165972   1459495408          71  530379753002097  8828892013fffff

[165973 rows x 4 columns]