<a href="https://colab.research.google.com/github/npappin-wsu/BroadbandDataQuickstart/blob/main/Broadband_Data_Quickstart_Hour_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Broadband Data Quickstart

## Setup

In [30]:
!git clone https://github.com/npappin-wsu/BroadbandDataQuickstart.git data
!git -C data pull

fatal: destination path 'data' already exists and is not an empty directory.
Already up to date.

In [31]:
!pip install -r data/requirements.txt

Requirement already satisfied: bdcdata in /usr/local/lib/python3.12/dist-packages (from -r data/requirements.txt (line 1)) (0.0.9)
Requirement already satisfied: h3pandas in /usr/local/lib/python3.12/dist-packages (from -r data/requirements.txt (line 2)) (0.3.0)
Requirement already satisfied: folium in /usr/local/lib/python3.12/dist-packages (from -r data/requirements.txt (line 3)) (0.20.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from -r data/requirements.txt (line 4)) (3.10.0)
Requirement already satisfied: mapclassify in /usr/local/lib/python3.12/dist-packages (from -r data/requirements.txt (line 5)) (2.10.0)
Requirement already satisfied: pygris in /usr/local/lib/python3.12/dist-packages (from -r data/requirements.txt (line 6)) (0.2.0)
Requirement already satisfied: pandas>=2 in /usr/local/lib/python3.12/dist-packages (from bdcdata->-r data/requirements.txt (line 1)) (2.2.2)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (from bdcdata->-r data/requirements.txt (line 1)) (18.1.0)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (from bdcdata->-r data/requirements.txt (line 1)) (1.1.1)
Requirement already satisfied: requests-ratelimiter in /usr/local/lib/python3.12/dist-packages (from bdcdata->-r data/requirements.txt (line 1)) (0.7.0)
Requirement already satisfied: geopandas in /usr/local/lib/python3.12/dist-packages (from h3pandas->-r data/requirements.txt (line 2)) (1.1.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from h3pandas->-r data/requirements.txt (line 2)) (2.0.2)
Requirement already satisfied: shapely in /usr/local/lib/python3.12/dist-packages (from h3pandas->-r data/requirements.txt (line 2)) (2.1.1)
Requirement already satisfied: h3>=4 in /usr/local/lib/python3.12/dist-packages (from h3pandas->-r data/requirements.txt (line 2)) (4.3.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from h3pandas->-r data/requirements.txt (line 2)) (4.15.0)
Requirement already satisfied: branca>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from folium->-r data/requirements.txt (line 3)) (0.8.1)
Requirement already satisfied: jinja2>=2.9 in /usr/local/lib/python3.12/dist-packages (from folium->-r data/requirements.txt (line 3)) (3.1.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from folium->-r data/requirements.txt (line 3)) (2.32.4)
Requirement already satisfied: xyzservices in /usr/local/lib/python3.12/dist-packages (from folium->-r data/requirements.txt (line 3)) (2025.4.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r data/requirements.txt (line 4)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r data/requirements.txt (line 4)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r data/requirements.txt (line 4)) (4.59.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r data/requirements.txt (line 4)) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r data/requirements.txt (line 4)) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r data/requirements.txt (line 4)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r data/requirements.txt (line 4)) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r data/requirements.txt (line 4)) (2.9.0.post0)
Requirement already satisfied: networkx>=3.2 in /usr/local/lib/python3.12/dist-packages (from mapclassify->-r data/requirements.txt (line 5)) (3.5)
Requirement already satisfied: scikit-learn>=1.4 in /usr/local/lib/python3.12/dist-packages (from mapclassify->-r data/requirements.txt (line 5)) (1.6.1)
Requirement already satisfied: scipy>=1.12 in /usr/local/lib/python3.12/dist-packages (from mapclassify->-r data/requirements.txt (line 5)) (1.16.1)
Requirement already satisfied: appdirs in /usr/local/lib/python3.12/dist-packages (from pygris->-r data/requirements.txt (line 6)) (1.4.4)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.12/dist-packages (from geopandas->h3pandas->-r data/requirements.txt (line 2)) (0.11.1)
Requirement already satisfied: pyproj>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from geopandas->h3pandas->-r data/requirements.txt (line 2)) (3.7.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.9->folium->-r data/requirements.txt (line 3)) (3.0.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2->bdcdata->-r data/requirements.txt (line 1)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2->bdcdata->-r data/requirements.txt (line 1)) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->-r data/requirements.txt (line 4)) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4->mapclassify->-r data/requirements.txt (line 5)) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4->mapclassify->-r data/requirements.txt (line 5)) (3.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->folium->-r data/requirements.txt (line 3)) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->folium->-r data/requirements.txt (line 3)) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->folium->-r data/requirements.txt (line 3)) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->folium->-r data/requirements.txt (line 3)) (2025.8.3)
Requirement already satisfied: pyrate-limiter<3.0 in /usr/local/lib/python3.12/dist-packages (from requests-ratelimiter->bdcdata->-r data/requirements.txt (line 1)) (2.10.0)

Setup API Keys first

In [32]:
import os, pathlib, h3pandas, pygris
from google.colab import userdata
import pandas as pd
import geopandas as gpd
os.environ["BDC_USERNAME"] = userdata.get('bdc_email')
os.environ["BDC_API_KEY"] = userdata.get('bdc_hash')

In [5]:
import bdcdata

{'User-Agent': 'python-bdc', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'hash_value': '2y/1NvvejDWWuZt4vXrkL9LQ4QNeprc1qPzW8w8Zvz0=', 'username': 'nick.pappin@wsu.edu'}
DEBUG:bdcdata:{'User-Agent': 'python-bdc', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'hash_value': '2y/1NvvejDWWuZt4vXrkL9LQ4QNeprc1qPzW8w8Zvz0=', 'username': 'nick.pappin@wsu.edu'}
Session created.
INFO:bdcdata:Session created.
Collecting metadata...
INFO:bdcdata:Collecting metadata...
{'data': [{'data_type': 'availability', 'as_of_date': '2022-06-30'}, {'data_type': 'availability', 'as_of_date': '2022-12-31'}, {'data_type': 'availability', 'as_of_date': '2023-06-30'}, {'data_type': 'availability', 'as_of_date': '2023-12-31'}, {'data_type': 'availability', 'as_of_date': '2024-06-30'}, {'data_type': 'availability', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2022-11-30'}, {'data_type': 'challenge', 'as_of_date': '2022-12-31'}, {'data_type': 'challenge', 'as_of_date': '2023-01-31'}, {'data_type': 'challenge', 'as_of_date': '2023-02-28'}, {'data_type': 'challenge', 'as_of_date': '2023-03-31'}, {'data_type': 'challenge', 'as_of_date': '2023-04-30'}, {'data_type': 'challenge', 'as_of_date': '2023-05-31'}, {'data_type': 'challenge', 'as_of_date': '2023-06-30'}, {'data_type': 'challenge', 'as_of_date': '2023-07-31'}, {'data_type': 'challenge', 'as_of_date': '2023-08-31'}, {'data_type': 'challenge', 'as_of_date': '2023-09-30'}, {'data_type': 'challenge', 'as_of_date': '2023-10-31'}, {'data_type': 'challenge', 'as_of_date': '2023-11-30'}, {'data_type': 'challenge', 'as_of_date': '2023-12-31'}, {'data_type': 'challenge', 'as_of_date': '2024-01-31'}, {'data_type': 'challenge', 'as_of_date': '2024-02-29'}, {'data_type': 'challenge', 'as_of_date': '2024-03-31'}, {'data_type': 'challenge', 'as_of_date': '2024-04-30'}, {'data_type': 'challenge', 'as_of_date': '2024-05-31'}, {'data_type': 'challenge', 'as_of_date': '2024-06-30'}, {'data_type': 'challenge', 'as_of_date': '2024-07-31'}, {'data_type': 'challenge', 'as_of_date': '2024-08-31'}, {'data_type': 'challenge', 'as_of_date': '2024-09-30'}, {'data_type': 'challenge', 'as_of_date': '2024-10-31'}, {'data_type': 'challenge', 'as_of_date': '2024-11-30'}, {'data_type': 'challenge', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2025-01-31'}, {'data_type': 'challenge', 'as_of_date': '2025-02-28'}, {'data_type': 'challenge', 'as_of_date': '2025-03-31'}, {'data_type': 'challenge', 'as_of_date': '2025-04-30'}, {'data_type': 'challenge', 'as_of_date': '2025-05-31'}, {'data_type': 'challenge', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2025-07-31'}, {'data_type': 'challenge', 'as_of_date': '2025-08-31'}], 'result_count': 40, 'status_code': 200, 'message': None, 'status': 'successful', 'request_date': '2025-09-10T18:27:40.720Z'}
DEBUG:bdcdata:{'data': [{'data_type': 'availability', 'as_of_date': '2022-06-30'}, {'data_type': 'availability', 'as_of_date': '2022-12-31'}, {'data_type': 'availability', 'as_of_date': '2023-06-30'}, {'data_type': 'availability', 'as_of_date': '2023-12-31'}, {'data_type': 'availability', 'as_of_date': '2024-06-30'}, {'data_type': 'availability', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2022-11-30'}, {'data_type': 'challenge', 'as_of_date': '2022-12-31'}, {'data_type': 'challenge', 'as_of_date': '2023-01-31'}, {'data_type': 'challenge', 'as_of_date': '2023-02-28'}, {'data_type': 'challenge', 'as_of_date': '2023-03-31'}, {'data_type': 'challenge', 'as_of_date': '2023-04-30'}, {'data_type': 'challenge', 'as_of_date': '2023-05-31'}, {'data_type': 'challenge', 'as_of_date': '2023-06-30'}, {'data_type': 'challenge', 'as_of_date': '2023-07-31'}, {'data_type': 'challenge', 'as_of_date': '2023-08-31'}, {'data_type': 'challenge', 'as_of_date': '2023-09-30'}, {'data_type': 'challenge', 'as_of_date': '2023-10-31'}, {'data_type': 'challenge', 'as_of_date': '2023-11-30'}, {'data_type': 'challenge', 'as_of_date': '2023-12-31'}, {'data_type': 'challenge', 'as_of_date': '2024-01-31'}, {'data_type': 'challenge', 'as_of_date': '2024-02-29'}, {'data_type': 'challenge', 'as_of_date': '2024-03-31'}, {'data_type': 'challenge', 'as_of_date': '2024-04-30'}, {'data_type': 'challenge', 'as_of_date': '2024-05-31'}, {'data_type': 'challenge', 'as_of_date': '2024-06-30'}, {'data_type': 'challenge', 'as_of_date': '2024-07-31'}, {'data_type': 'challenge', 'as_of_date': '2024-08-31'}, {'data_type': 'challenge', 'as_of_date': '2024-09-30'}, {'data_type': 'challenge', 'as_of_date': '2024-10-31'}, {'data_type': 'challenge', 'as_of_date': '2024-11-30'}, {'data_type': 'challenge', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2025-01-31'}, {'data_type': 'challenge', 'as_of_date': '2025-02-28'}, {'data_type': 'challenge', 'as_of_date': '2025-03-31'}, {'data_type': 'challenge', 'as_of_date': '2025-04-30'}, {'data_type': 'challenge', 'as_of_date': '2025-05-31'}, {'data_type': 'challenge', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2025-07-31'}, {'data_type': 'challenge', 'as_of_date': '2025-08-31'}], 'result_count': 40, 'status_code': 200, 'message': None, 'status': 'successful', 'request_date': '2025-09-10T18:27:40.720Z'}
{'data': [{'data_type': 'availability', 'as_of_date': '2022-06-30'}, {'data_type': 'availability', 'as_of_date': '2022-12-31'}, {'data_type': 'availability', 'as_of_date': '2023-06-30'}, {'data_type': 'availability', 'as_of_date': '2023-12-31'}, {'data_type': 'availability', 'as_of_date': '2024-06-30'}, {'data_type': 'availability', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2022-11-30'}, {'data_type': 'challenge', 'as_of_date': '2022-12-31'}, {'data_type': 'challenge', 'as_of_date': '2023-01-31'}, {'data_type': 'challenge', 'as_of_date': '2023-02-28'}, {'data_type': 'challenge', 'as_of_date': '2023-03-31'}, {'data_type': 'challenge', 'as_of_date': '2023-04-30'}, {'data_type': 'challenge', 'as_of_date': '2023-05-31'}, {'data_type': 'challenge', 'as_of_date': '2023-06-30'}, {'data_type': 'challenge', 'as_of_date': '2023-07-31'}, {'data_type': 'challenge', 'as_of_date': '2023-08-31'}, {'data_type': 'challenge', 'as_of_date': '2023-09-30'}, {'data_type': 'challenge', 'as_of_date': '2023-10-31'}, {'data_type': 'challenge', 'as_of_date': '2023-11-30'}, {'data_type': 'challenge', 'as_of_date': '2023-12-31'}, {'data_type': 'challenge', 'as_of_date': '2024-01-31'}, {'data_type': 'challenge', 'as_of_date': '2024-02-29'}, {'data_type': 'challenge', 'as_of_date': '2024-03-31'}, {'data_type': 'challenge', 'as_of_date': '2024-04-30'}, {'data_type': 'challenge', 'as_of_date': '2024-05-31'}, {'data_type': 'challenge', 'as_of_date': '2024-06-30'}, {'data_type': 'challenge', 'as_of_date': '2024-07-31'}, {'data_type': 'challenge', 'as_of_date': '2024-08-31'}, {'data_type': 'challenge', 'as_of_date': '2024-09-30'}, {'data_type': 'challenge', 'as_of_date': '2024-10-31'}, {'data_type': 'challenge', 'as_of_date': '2024-11-30'}, {'data_type': 'challenge', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2025-01-31'}, {'data_type': 'challenge', 'as_of_date': '2025-02-28'}, {'data_type': 'challenge', 'as_of_date': '2025-03-31'}, {'data_type': 'challenge', 'as_of_date': '2025-04-30'}, {'data_type': 'challenge', 'as_of_date': '2025-05-31'}, {'data_type': 'challenge', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2025-07-31'}, {'data_type': 'challenge', 'as_of_date': '2025-08-31'}], 'result_count': 40, 'status_code': 200, 'message': None, 'status': 'successful', 'request_date': '2025-09-10T18:27:40.720Z'}
INFO:bdcdata:{'data': [{'data_type': 'availability', 'as_of_date': '2022-06-30'}, {'data_type': 'availability', 'as_of_date': '2022-12-31'}, {'data_type': 'availability', 'as_of_date': '2023-06-30'}, {'data_type': 'availability', 'as_of_date': '2023-12-31'}, {'data_type': 'availability', 'as_of_date': '2024-06-30'}, {'data_type': 'availability', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2022-11-30'}, {'data_type': 'challenge', 'as_of_date': '2022-12-31'}, {'data_type': 'challenge', 'as_of_date': '2023-01-31'}, {'data_type': 'challenge', 'as_of_date': '2023-02-28'}, {'data_type': 'challenge', 'as_of_date': '2023-03-31'}, {'data_type': 'challenge', 'as_of_date': '2023-04-30'}, {'data_type': 'challenge', 'as_of_date': '2023-05-31'}, {'data_type': 'challenge', 'as_of_date': '2023-06-30'}, {'data_type': 'challenge', 'as_of_date': '2023-07-31'}, {'data_type': 'challenge', 'as_of_date': '2023-08-31'}, {'data_type': 'challenge', 'as_of_date': '2023-09-30'}, {'data_type': 'challenge', 'as_of_date': '2023-10-31'}, {'data_type': 'challenge', 'as_of_date': '2023-11-30'}, {'data_type': 'challenge', 'as_of_date': '2023-12-31'}, {'data_type': 'challenge', 'as_of_date': '2024-01-31'}, {'data_type': 'challenge', 'as_of_date': '2024-02-29'}, {'data_type': 'challenge', 'as_of_date': '2024-03-31'}, {'data_type': 'challenge', 'as_of_date': '2024-04-30'}, {'data_type': 'challenge', 'as_of_date': '2024-05-31'}, {'data_type': 'challenge', 'as_of_date': '2024-06-30'}, {'data_type': 'challenge', 'as_of_date': '2024-07-31'}, {'data_type': 'challenge', 'as_of_date': '2024-08-31'}, {'data_type': 'challenge', 'as_of_date': '2024-09-30'}, {'data_type': 'challenge', 'as_of_date': '2024-10-31'}, {'data_type': 'challenge', 'as_of_date': '2024-11-30'}, {'data_type': 'challenge', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2025-01-31'}, {'data_type': 'challenge', 'as_of_date': '2025-02-28'}, {'data_type': 'challenge', 'as_of_date': '2025-03-31'}, {'data_type': 'challenge', 'as_of_date': '2025-04-30'}, {'data_type': 'challenge', 'as_of_date': '2025-05-31'}, {'data_type': 'challenge', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2025-07-31'}, {'data_type': 'challenge', 'as_of_date': '2025-08-31'}], 'result_count': 40, 'status_code': 200, 'message': None, 'status': 'successful', 'request_date': '2025-09-10T18:27:40.720Z'}
[{'data_type': 'availability', 'as_of_date': '2022-06-30'}, {'data_type': 'availability', 'as_of_date': '2022-12-31'}, {'data_type': 'availability', 'as_of_date': '2023-06-30'}, {'data_type': 'availability', 'as_of_date': '2023-12-31'}, {'data_type': 'availability', 'as_of_date': '2024-06-30'}, {'data_type': 'availability', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2022-11-30'}, {'data_type': 'challenge', 'as_of_date': '2022-12-31'}, {'data_type': 'challenge', 'as_of_date': '2023-01-31'}, {'data_type': 'challenge', 'as_of_date': '2023-02-28'}, {'data_type': 'challenge', 'as_of_date': '2023-03-31'}, {'data_type': 'challenge', 'as_of_date': '2023-04-30'}, {'data_type': 'challenge', 'as_of_date': '2023-05-31'}, {'data_type': 'challenge', 'as_of_date': '2023-06-30'}, {'data_type': 'challenge', 'as_of_date': '2023-07-31'}, {'data_type': 'challenge', 'as_of_date': '2023-08-31'}, {'data_type': 'challenge', 'as_of_date': '2023-09-30'}, {'data_type': 'challenge', 'as_of_date': '2023-10-31'}, {'data_type': 'challenge', 'as_of_date': '2023-11-30'}, {'data_type': 'challenge', 'as_of_date': '2023-12-31'}, {'data_type': 'challenge', 'as_of_date': '2024-01-31'}, {'data_type': 'challenge', 'as_of_date': '2024-02-29'}, {'data_type': 'challenge', 'as_of_date': '2024-03-31'}, {'data_type': 'challenge', 'as_of_date': '2024-04-30'}, {'data_type': 'challenge', 'as_of_date': '2024-05-31'}, {'data_type': 'challenge', 'as_of_date': '2024-06-30'}, {'data_type': 'challenge', 'as_of_date': '2024-07-31'}, {'data_type': 'challenge', 'as_of_date': '2024-08-31'}, {'data_type': 'challenge', 'as_of_date': '2024-09-30'}, {'data_type': 'challenge', 'as_of_date': '2024-10-31'}, {'data_type': 'challenge', 'as_of_date': '2024-11-30'}, {'data_type': 'challenge', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2025-01-31'}, {'data_type': 'challenge', 'as_of_date': '2025-02-28'}, {'data_type': 'challenge', 'as_of_date': '2025-03-31'}, {'data_type': 'challenge', 'as_of_date': '2025-04-30'}, {'data_type': 'challenge', 'as_of_date': '2025-05-31'}, {'data_type': 'challenge', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2025-07-31'}, {'data_type': 'challenge', 'as_of_date': '2025-08-31'}]
DEBUG:bdcdata:[{'data_type': 'availability', 'as_of_date': '2022-06-30'}, {'data_type': 'availability', 'as_of_date': '2022-12-31'}, {'data_type': 'availability', 'as_of_date': '2023-06-30'}, {'data_type': 'availability', 'as_of_date': '2023-12-31'}, {'data_type': 'availability', 'as_of_date': '2024-06-30'}, {'data_type': 'availability', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2022-11-30'}, {'data_type': 'challenge', 'as_of_date': '2022-12-31'}, {'data_type': 'challenge', 'as_of_date': '2023-01-31'}, {'data_type': 'challenge', 'as_of_date': '2023-02-28'}, {'data_type': 'challenge', 'as_of_date': '2023-03-31'}, {'data_type': 'challenge', 'as_of_date': '2023-04-30'}, {'data_type': 'challenge', 'as_of_date': '2023-05-31'}, {'data_type': 'challenge', 'as_of_date': '2023-06-30'}, {'data_type': 'challenge', 'as_of_date': '2023-07-31'}, {'data_type': 'challenge', 'as_of_date': '2023-08-31'}, {'data_type': 'challenge', 'as_of_date': '2023-09-30'}, {'data_type': 'challenge', 'as_of_date': '2023-10-31'}, {'data_type': 'challenge', 'as_of_date': '2023-11-30'}, {'data_type': 'challenge', 'as_of_date': '2023-12-31'}, {'data_type': 'challenge', 'as_of_date': '2024-01-31'}, {'data_type': 'challenge', 'as_of_date': '2024-02-29'}, {'data_type': 'challenge', 'as_of_date': '2024-03-31'}, {'data_type': 'challenge', 'as_of_date': '2024-04-30'}, {'data_type': 'challenge', 'as_of_date': '2024-05-31'}, {'data_type': 'challenge', 'as_of_date': '2024-06-30'}, {'data_type': 'challenge', 'as_of_date': '2024-07-31'}, {'data_type': 'challenge', 'as_of_date': '2024-08-31'}, {'data_type': 'challenge', 'as_of_date': '2024-09-30'}, {'data_type': 'challenge', 'as_of_date': '2024-10-31'}, {'data_type': 'challenge', 'as_of_date': '2024-11-30'}, {'data_type': 'challenge', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2025-01-31'}, {'data_type': 'challenge', 'as_of_date': '2025-02-28'}, {'data_type': 'challenge', 'as_of_date': '2025-03-31'}, {'data_type': 'challenge', 'as_of_date': '2025-04-30'}, {'data_type': 'challenge', 'as_of_date': '2025-05-31'}, {'data_type': 'challenge', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2025-07-31'}, {'data_type': 'challenge', 'as_of_date': '2025-08-31'}]
Metadata collected.
INFO:bdcdata:Metadata collected.
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2022-11-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2022-11-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2022-12-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2022-12-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-01-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-01-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-02-28'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-02-28'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-03-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-03-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-04-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-04-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-05-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-05-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-06-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-06-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-07-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-07-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-08-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-08-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-09-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-09-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-10-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-10-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-11-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-11-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-12-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-12-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-01-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-01-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-02-29'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-02-29'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-03-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-03-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-04-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-04-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-05-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-05-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-06-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-06-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-07-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-07-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-08-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-08-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-09-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-09-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-10-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-10-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-11-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-11-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-12-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-12-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2025-01-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2025-01-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2025-02-28'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2025-02-28'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2025-03-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2025-03-31'}
Data type: challenge

## Pull data

In [6]:
waData = bdcdata.availability.fixed(states=[53], technology='fixed', release=['2024-12-31'], cache=True)

Collecting availability...
INFO:bdcdata:Collecting availability...
State: [53]
DEBUG:bdcdata:State: [53]
Technology: fixed
DEBUG:bdcdata:Technology: fixed
Release: ['2024-12-31']
DEBUG:bdcdata:Release: ['2024-12-31']
State: Washington({'file_id': 1224952, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '10', 'technology_code_desc': 'Copper', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_Copper_fixed_broadband_D24_03sep2025', 'record_count': '1102663'})), Technology: 10, Release: 2024-12-31
DEBUG:bdcdata:State: Washington({'file_id': 1224952, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '10', 'technology_code_desc': 'Copper', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_Copper_fixed_broadband_D24_03sep2025', 'record_count': '1102663'})), Technology: 10, Release: 2024-12-31
State: Washington({'file_id': 1225006, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '40', 'technology_code_desc': 'Cable', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_Cable_fixed_broadband_D24_03sep2025', 'record_count': '2296180'})), Technology: 40, Release: 2024-12-31
DEBUG:bdcdata:State: Washington({'file_id': 1225006, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '40', 'technology_code_desc': 'Cable', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_Cable_fixed_broadband_D24_03sep2025', 'record_count': '2296180'})), Technology: 40, Release: 2024-12-31
State: Washington({'file_id': 1225062, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '50', 'technology_code_desc': 'Fiber to the Premises', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_FibertothePremises_fixed_broadband_D24_03sep2025', 'record_count': '1094956'})), Technology: 50, Release: 2024-12-31
DEBUG:bdcdata:State: Washington({'file_id': 1225062, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '50', 'technology_code_desc': 'Fiber to the Premises', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_FibertothePremises_fixed_broadband_D24_03sep2025', 'record_count': '1094956'})), Technology: 50, Release: 2024-12-31
State: Washington({'file_id': 1225118, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '60', 'technology_code_desc': 'GSO Satellite', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_GSOSatellite_fixed_broadband_D24_03sep2025', 'record_count': '7707217'})), Technology: 60, Release: 2024-12-31
DEBUG:bdcdata:State: Washington({'file_id': 1225118, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '60', 'technology_code_desc': 'GSO Satellite', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_GSOSatellite_fixed_broadband_D24_03sep2025', 'record_count': '7707217'})), Technology: 60, Release: 2024-12-31
State: Washington({'file_id': 1225171, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '61', 'technology_code_desc': 'NGSO Satellite', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_NGSOSatellite_fixed_broadband_D24_03sep2025', 'record_count': '2565799'})), Technology: 61, Release: 2024-12-31
DEBUG:bdcdata:State: Washington({'file_id': 1225171, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '61', 'technology_code_desc': 'NGSO Satellite', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_NGSOSatellite_fixed_broadband_D24_03sep2025', 'record_count': '2565799'})), Technology: 61, Release: 2024-12-31
State: Washington({'file_id': 1225226, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '70', 'technology_code_desc': 'Unlicensed Fixed Wireless', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_UnlicensedFixedWireless_fixed_broadband_D24_03sep2025', 'record_count': '1308505'})), Technology: 70, Release: 2024-12-31
DEBUG:bdcdata:State: Washington({'file_id': 1225226, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '70', 'technology_code_desc': 'Unlicensed Fixed Wireless', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_UnlicensedFixedWireless_fixed_broadband_D24_03sep2025', 'record_count': '1308505'})), Technology: 70, Release: 2024-12-31
State: Washington({'file_id': 1225281, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '71', 'technology_code_desc': 'Licensed Fixed Wireless', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_LicensedFixedWireless_fixed_broadband_D24_03sep2025', 'record_count': '3607054'})), Technology: 71, Release: 2024-12-31
DEBUG:bdcdata:State: Washington({'file_id': 1225281, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '71', 'technology_code_desc': 'Licensed Fixed Wireless', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_LicensedFixedWireless_fixed_broadband_D24_03sep2025', 'record_count': '3607054'})), Technology: 71, Release: 2024-12-31
State: Washington({'file_id': 1225331, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '72', 'technology_code_desc': 'LBR Fixed Wireless', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_LBRFixedWireless_fixed_broadband_D24_03sep2025', 'record_count': '170852'})), Technology: 72, Release: 2024-12-31
DEBUG:bdcdata:State: Washington({'file_id': 1225331, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '72', 'technology_code_desc': 'LBR Fixed Wireless', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_LBRFixedWireless_fixed_broadband_D24_03sep2025', 'record_count': '170852'})), Technology: 72, Release: 2024-12-31
State: ['53'], Technology: ['0', '10', '40', '50', '60', '61', '70', '71', '72'], Release: ['2024-12-31']
DEBUG:bdcdata:State: ['53'], Technology: ['0', '10', '40', '50', '60', '61', '70', '71', '72'], Release: ['2024-12-31']

In [23]:
waData.sample(n=20)

,frn,provider_id,brand_name,location_id,technology,max_advertised_download_speed,max_advertised_upload_speed,low_latency,business_residential_code,state_usps,block_geoid,h3_res8_id
1884593,0025646373,130235,Spectrum,1296176378,40,1000,35,True,B,WA,530210202011022,882888b983fffff
15907431,0026832444,380048,Gigabeam Internet,1305915305,70,300,300,True,X,WA,530779400051023,88288982a1fffff
2211245,0003768165,130317,Xfinity,1073184797,40,1200,35,True,X,WA,530350907004006,8828d54687fffff
2283842,0003768165,130317,Xfinity,1073193160,40,2000,300,True,X,WA,530350802001027,8828d50b1bfffff
12822411,0026043968,430076,Starlink,1349416371,61,100,25,True,R,WA,530110405052024,8828f07317fffff
11891462,0004963088,290111,Viasat Inc,1366810740,60,100,3,False,R,WA,530330292082004,8828d5c835fffff
17445737,0005937974,130077,AT&T,1367067485,71,25,3,True,R,WA,530330110022023,8828d5508dfffff
7281473,0004963088,290111,Viasat Inc,1330205050,60,100,3,False,R,WA,530530707035000,8828d5d8dbfffff
15259700,0023973480,290093,Pogozone powered by Neubeam,1310106822,70,40,7,True,X,WA,530730007001021,8828d17b69fffff
14008661,0026043968,430076,Starlink,1312946203,61,100,25,True,R,WA,530579524031006,8828d1526dfffff
11895990,0004963088,290111,Viasat Inc,1337020607,60,100,4,False,B,WA,530610519134003,8828d54c03fffff
10024992,0004963088,290111,Viasat Inc,1367030480,60,100,4,False,B,WA,530330308022009,8828d5d991fffff
10464686,0004963088,290111,Viasat Inc,1409383579,60,50,3,False,R,WA,530210206062010,882888aac3fffff
16924598,0006945950,130403,T-Mobile,1073202160,71,0,0,True,X,WA,530350917011004,8828d50827fffff
17564133,0018506568,131425,Verizon,1310115916,71,300,20,True,R,WA,530730012021030,8828d14095fffff
1712965,0008245839,130079,Astound Broadband,1366578320,40,1500,50,True,X,WA,530330059023019,8828d54291fffff
18271924,0005937974,130077,AT&T,1366594089,71,25,3,True,R,WA,530330056003030,8828d555b5fffff
15429616,0033107137,260010,Wind Wireless,1451834942,70,100,20,True,X,WA,530630130033005,8812db38a3fffff
4686155,0004963088,290111,Viasat Inc,1342668274,60,100,4,False,B,WA,530630135033018,8812db7423fffff
4610139,0012369286,130627,HughesNet,1337083088,60,100,5,False,X,WA,530610525052007,8828d0a233fffff

In [7]:
waData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19853226 entries, 0 to 19853225
Data columns (total 12 columns):
 #   Column                         Dtype
---  ------                         -----
 0   frn                            object
 1   provider_id                    UInt32
 2   brand_name                     object
 3   location_id                    UInt32
 4   technology                     UInt16
 5   max_advertised_download_speed  UInt32
 6   max_advertised_upload_speed    UInt32
 7   low_latency                    boolean
 8   business_residential_code      string[pyarrow]
 9   state_usps                     category
 10  block_geoid                    object
 11  h3_res8_id                     object
dtypes: UInt16(1), UInt32(4), boolean(1), category(1), object(4), string[pyarrow](1)
memory usage: 1.2+ GB

In [8]:
locationLookup = waData[['location_id', 'block_geoid', 'h3_res8_id']].drop_duplicates(ignore_index=True)

In [9]:
locationLookup

         location_id      block_geoid       h3_res8_id
0         1027407142  530519705001008  8812db8c59fffff
1         1121311109  530179508002000  8828d68111fffff
2         1122544844  530199702002003  8812da8343fffff
3         1296237355  530079604001044  8828d60c6dfffff
4         1296248370  530299710001051  8828d1d5d1fffff
...              ...              ...              ...
2566302   1564174977  530079603021002  8828d6081bfffff
2566303   1564299037  530459604031000  8828d51231fffff
2566304   1342737372  530630104032044  8812db701dfffff
2566305   1342746597  530630112024002  8812db0cdbfffff
2566306   1349409498  530110405043001  8828f07365fffff

[2566307 rows x 3 columns]

## Census Data

In [33]:
washington = pygris.blocks(state='53')

Using the default year of 2024
HTTP download failed, trying FTP as fallback...
Downloading tl_2024_53_tabblock20.zip from Census FTP...

## H3 Data

In [10]:
fpLocations = pd.read_csv(pathlib.Path('data', 'fp_locations.csv'))

In [11]:
fpLocations.drop_duplicates()

,location_id,project_id,classification,technology,upload_speed_anticipated,download_speed_anticipated,low_latency
0,1024099225,CM61-BEAD-WA-26-96212-001,0,61,20,150,1
1,1024099256,CM61-BEAD-WA-26-96212-001,0,61,20,150,1
2,1024099803,CM61-BEAD-WA-26-96212-001,0,61,20,150,1
3,1024099831,CM61-BEAD-WA-26-96212-001,0,61,20,150,1
4,1024099838,CM61-BEAD-WA-26-96212-001,0,61,20,150,1
...,...,...,...,...,...,...,...
165968,1414834970,CM61-BEAD-WA-26-96212-171,0,71,20,100,1
165969,1414834977,CM61-BEAD-WA-26-96212-171,0,71,20,100,1
165970,1414835005,CM61-BEAD-WA-26-96212-171,0,71,20,100,1
165971,1414835015,CM61-BEAD-WA-26-96212-171,0,50,1000,1000,1
165972,1459495408,CM61-BEAD-WA-26-96212-171,0,71,20,100,1

In [12]:
locations = fpLocations[['location_id', 'technology']].merge(locationLookup, how='left', on='location_id')

In [13]:
locations.shape

(165973, 4)

In [14]:
locations.drop_duplicates()

        location_id  technology      block_geoid       h3_res8_id
0        1024099225          61  530019501001104  88288b1169fffff
1        1024099256          61  530019503011093  8828882d85fffff
2        1024099803          61  530019501001244  88288a2621fffff
3        1024099831          61  530019501001158  88288bc603fffff
4        1024099838          61  530019502002050  88288b8f5bfffff
...             ...         ...              ...              ...
165968   1414834970          71  530379753003007  8828892c1bfffff
165969   1414834977          71  530379753001078  88288921a9fffff
165970   1414835005          71  530379753001085  8828892033fffff
165971   1414835015          50  530379753001116  8828892a1bfffff
165972   1459495408          71  530379753002097  8828892013fffff

[165972 rows x 4 columns]

In [15]:
pivoted = locations[['h3_res8_id', 'technology', 'location_id']].pivot_table(index='h3_res8_id', columns='technology', values='location_id', aggfunc='count', fill_value=0, )

In [16]:
pivoted

technology       50  61  70  71  72
h3_res8_id
8812d80013fffff   0   0   0   3   0
8812d80017fffff   0   0   0   2   0
8812d8001bfffff   0   0   0   1   0
8812d80081fffff   0   0   0   4   0
8812d80085fffff   0   0   0   2   0
...              ..  ..  ..  ..  ..
8828f66f1bfffff   0   1   0   0   0
8828f66f43fffff   0   3   0   0   0
8828f66f53fffff   0   3   0   0   0
8828f66f55fffff   0   1   0   0   0
8828f66f5dfffff   0   1   0   0   0

[35178 rows x 5 columns]

In [17]:
pivoted.to_excel('test.xlsx')

In [18]:
pivoted.info()

<class 'pandas.core.frame.DataFrame'>
Index: 35178 entries, 8812d80013fffff to 8828f66f5dfffff
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   50      35178 non-null  int64
 1   61      35178 non-null  int64
 2   70      35178 non-null  int64
 3   71      35178 non-null  int64
 4   72      35178 non-null  int64
dtypes: int64(5)
memory usage: 1.6+ MB

In [19]:
pivoted['70s'] = pivoted.loc[:, 70] + pivoted.loc[:, 71] + pivoted.loc[:, 72]

In [26]:
pivoted['max'] = pivoted[[50, "70s", 61]].idxmax(axis=1, )

TypeError: 'StringMethods' object is not callable

In [25]:
gpd.GeoDataFrame(pivoted.h3.h3_to_geo_boundary()).explore(column='max', categorical=True)

technology,50,61,70,71,72,70s,max,geometry
h3_res8_id,,,,,,,,
8812d80013fffff,0,0,0,3,0,3,70s,"POLYGON ((-117.38523 48.86208, -117.37987 48.8..."
8812d80017fffff,0,0,0,2,0,2,70s,"POLYGON ((-117.39737 48.86012, -117.39201 48.8..."
8812d8001bfffff,0,0,0,1,0,1,70s,"POLYGON ((-117.38522 48.87794, -117.38947 48.8..."
8812d80081fffff,0,0,0,4,0,4,70s,"POLYGON ((-117.36462 48.83885, -117.35926 48.8..."
8812d80085fffff,0,0,0,2,0,2,70s,"POLYGON ((-117.37676 48.83689, -117.37139 48.8..."
...,...,...,...,...,...,...,...,...
8828f66f1bfffff,0,1,0,0,0,0,61,"POLYGON ((-121.15804 45.63384, -121.15311 45.6..."
8828f66f43fffff,0,3,0,0,0,0,61,"POLYGON ((-121.12613 45.6126, -121.12119 45.61..."
8828f66f53fffff,0,3,0,0,0,0,61,"POLYGON ((-121.15348 45.62088, -121.14854 45.6..."
8828f66f55fffff,0,1,0,0,0,0,61,"POLYGON ((-121.13411 45.61791, -121.12917 45.6..."
8828f66f5dfffff,0,1,0,0,0,0,61,"POLYGON ((-121.13753 45.61025, -121.13259 45.6..."