<a href="https://colab.research.google.com/github/npappin-wsu/BroadbandDataQuickstart/blob/main/Broadband_Data_Quickstart_Hour_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Broadband Data Quickstart

## Setup

In [2]:
!git clone https://github.com/npappin-wsu/BroadbandDataQuickstart.git data
!git -C data pull
!wget -O cache.tar.gz https://www.dropbox.com/scl/fi/8omgvvnk5mjykugdgau26/cache.tar?rlkey=huo2qmtwxzoj50gqujiql1pc4&st=q8bp03ab&dl=0
!tar xvzf cache.tar.gz

fatal: destination path 'data' already exists and is not an empty directory.
Already up to date.
--2025-09-18 03:49:10--  https://www.dropbox.com/scl/fi/8omgvvnk5mjykugdgau26/cache.tar?rlkey=huo2qmtwxzoj50gqujiql1pc4
Resolving www.dropbox.com (www.dropbox.com)... 162.125.69.18, 2620:100:6022:18::a27d:4212
Connecting to www.dropbox.com (www.dropbox.com)|162.125.69.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://uc5e2fe6db22d7a802e07c56c145.dl.dropboxusercontent.com/cd/0/inline/Cxmey-3tV_egKc8HEB-vEBTm4KFVUD32rv_KW6G2LxGnqagRQ_BG1rcu2TvYfqlWCvQYYndSYANQybgo_hy-lVfOeZPxUVRc4_RO4UlEN-kuPdcZUDp_5JVHD12tQgUihCY/file# [following]
--2025-09-18 03:49:11--  https://uc5e2fe6db22d7a802e07c56c145.dl.dropboxusercontent.com/cd/0/inline/Cxmey-3tV_egKc8HEB-vEBTm4KFVUD32rv_KW6G2LxGnqagRQ_BG1rcu2TvYfqlWCvQYYndSYANQybgo_hy-lVfOeZPxUVRc4_RO4UlEN-kuPdcZUDp_5JVHD12tQgUihCY/file
Resolving uc5e2fe6db22d7a802e07c56c145.dl.dropboxusercontent.com (uc5e2fe6db22d7a802e07c56c145.dl.dropboxusercontent.com)... 162.125.65.15, 2620:100:6023:15::a27d:430f
Connecting to uc5e2fe6db22d7a802e07c56c145.dl.dropboxusercontent.com (uc5e2fe6db22d7a802e07c56c145.dl.dropboxusercontent.com)|162.125.65.15|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /cd/0/inline2/CxlzSjIYLsKFS7nryVHGmdqp2DdG3zqO9HikB44cssXhCxSrLXsfe9GA3n1Hj128LGefZuCsAXaabT17cSl9qsG59k5JecHC7xXdsNsJX00JvLmxFSAdr-53s9L8W4qviWi4__V8wHncD6obzXcsus1EP3xFuZfluvB4L4d7HE9XKDxh3L_zT7i0E4QBQUFvvKszX-3GrdLZMo6KVYhyzqJ-hku20h1HnGqbPaLlxIRz-A1_F5fKDKPiT0dzCSf-VAzymMEudbb7q72nrebtuYEg9UNkWMRo54--Wn_omWjE87dVUeQQNdn5rDkPCTAFHBkJAMypllA4nWggo0HGA7nsUzGLJTBhWw8cdc9o9rIDpw/file [following]
--2025-09-18 03:49:12--  https://uc5e2fe6db22d7a802e07c56c145.dl.dropboxusercontent.com/cd/0/inline2/CxlzSjIYLsKFS7nryVHGmdqp2DdG3zqO9HikB44cssXhCxSrLXsfe9GA3n1Hj128LGefZuCsAXaabT17cSl9qsG59k5JecHC7xXdsNsJX00JvLmxFSAdr-53s9L8W4qviWi4__V8wHncD6obzXcsus1EP3xFuZfluvB4L4d7HE9XKDxh3L_zT7i0E4QBQUFvvKszX-3GrdLZMo6KVYhyzqJ-hku20h1HnGqbPaLlxIRz-A1_F5fKDKPiT0dzCSf-VAzymMEudbb7q72nrebtuYEg9UNkWMRo54--Wn_omWjE87dVUeQQNdn5rDkPCTAFHBkJAMypllA4nWggo0HGA7nsUzGLJTBhWw8cdc9o9rIDpw/file
Reusing existing connection to uc5e2fe6db22d7a802e07c56c145.dl.dropboxusercontent.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 938078208 (895M) [application/x-tar]
Saving to: ‘cache.tar.gz’

cache.tar.gz        100%[===================>] 894.62M  35.1MB/s    in 25s

2025-09-18 03:49:37 (35.3 MB/s) - ‘cache.tar.gz’ saved [938078208/938078208]


gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

In [2]:
!pip install -r data/requirements.txt

Collecting bdcdata (from -r data/requirements.txt (line 1))
  Downloading bdcdata-0.0.10-py3-none-any.whl.metadata (901 bytes)
Collecting h3pandas (from -r data/requirements.txt (line 2))
  Downloading h3pandas-0.3.0-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: folium in /usr/local/lib/python3.12/dist-packages (from -r data/requirements.txt (line 3)) (0.20.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from -r data/requirements.txt (line 4)) (3.10.0)
Collecting mapclassify (from -r data/requirements.txt (line 5))
  Downloading mapclassify-2.10.0-py3-none-any.whl.metadata (3.1 kB)
Collecting pygris (from -r data/requirements.txt (line 6))
  Downloading pygris-0.2.0-py3-none-any.whl.metadata (2.3 kB)
Collecting ndtguide (from -r data/requirements.txt (line 7))
  Downloading ndtguide-0.1.1-py3-none-any.whl.metadata (7.8 kB)
Collecting awscli (from -r data/requirements.txt (line 8))
  Downloading awscli-1.42.33-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: pandas>=2 in /usr/local/lib/python3.12/dist-packages (from bdcdata->-r data/requirements.txt (line 1)) (2.2.2)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (from bdcdata->-r data/requirements.txt (line 1)) (18.1.0)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (from bdcdata->-r data/requirements.txt (line 1)) (1.1.1)
Collecting requests-ratelimiter (from bdcdata->-r data/requirements.txt (line 1))
  Downloading requests_ratelimiter-0.7.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: geopandas in /usr/local/lib/python3.12/dist-packages (from h3pandas->-r data/requirements.txt (line 2)) (1.1.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from h3pandas->-r data/requirements.txt (line 2)) (2.0.2)
Requirement already satisfied: shapely in /usr/local/lib/python3.12/dist-packages (from h3pandas->-r data/requirements.txt (line 2)) (2.1.1)
Collecting h3>=4 (from h3pandas->-r data/requirements.txt (line 2))
  Downloading h3-4.3.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (18 kB)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from h3pandas->-r data/requirements.txt (line 2)) (4.15.0)
Requirement already satisfied: branca>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from folium->-r data/requirements.txt (line 3)) (0.8.1)
Requirement already satisfied: jinja2>=2.9 in /usr/local/lib/python3.12/dist-packages (from folium->-r data/requirements.txt (line 3)) (3.1.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from folium->-r data/requirements.txt (line 3)) (2.32.4)
Requirement already satisfied: xyzservices in /usr/local/lib/python3.12/dist-packages (from folium->-r data/requirements.txt (line 3)) (2025.4.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r data/requirements.txt (line 4)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r data/requirements.txt (line 4)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r data/requirements.txt (line 4)) (4.59.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r data/requirements.txt (line 4)) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r data/requirements.txt (line 4)) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r data/requirements.txt (line 4)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r data/requirements.txt (line 4)) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r data/requirements.txt (line 4)) (2.9.0.post0)
Requirement already satisfied: networkx>=3.2 in /usr/local/lib/python3.12/dist-packages (from mapclassify->-r data/requirements.txt (line 5)) (3.5)
Requirement already satisfied: scikit-learn>=1.4 in /usr/local/lib/python3.12/dist-packages (from mapclassify->-r data/requirements.txt (line 5)) (1.6.1)
Requirement already satisfied: scipy>=1.12 in /usr/local/lib/python3.12/dist-packages (from mapclassify->-r data/requirements.txt (line 5)) (1.16.1)
Collecting appdirs (from pygris->-r data/requirements.txt (line 6))
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting botocore==1.40.33 (from awscli->-r data/requirements.txt (line 8))
  Downloading botocore-1.40.33-py3-none-any.whl.metadata (5.7 kB)
Collecting docutils<=0.19,>=0.18.1 (from awscli->-r data/requirements.txt (line 8))
  Downloading docutils-0.19-py3-none-any.whl.metadata (2.7 kB)
Collecting s3transfer<0.15.0,>=0.14.0 (from awscli->-r data/requirements.txt (line 8))
  Downloading s3transfer-0.14.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: PyYAML<6.1,>=3.10 in /usr/local/lib/python3.12/dist-packages (from awscli->-r data/requirements.txt (line 8)) (6.0.2)
Collecting colorama<0.4.7,>=0.2.5 (from awscli->-r data/requirements.txt (line 8))
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting rsa<4.8,>=3.1.2 (from awscli->-r data/requirements.txt (line 8))
  Downloading rsa-4.7.2-py3-none-any.whl.metadata (3.6 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from botocore==1.40.33->awscli->-r data/requirements.txt (line 8))
  Downloading jmespath-1.0.1-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.12/dist-packages (from botocore==1.40.33->awscli->-r data/requirements.txt (line 8)) (2.5.0)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.12/dist-packages (from geopandas->h3pandas->-r data/requirements.txt (line 2)) (0.11.1)
Requirement already satisfied: pyproj>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from geopandas->h3pandas->-r data/requirements.txt (line 2)) (3.7.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.9->folium->-r data/requirements.txt (line 3)) (3.0.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2->bdcdata->-r data/requirements.txt (line 1)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2->bdcdata->-r data/requirements.txt (line 1)) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->-r data/requirements.txt (line 4)) (1.17.0)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/local/lib/python3.12/dist-packages (from rsa<4.8,>=3.1.2->awscli->-r data/requirements.txt (line 8)) (0.6.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4->mapclassify->-r data/requirements.txt (line 5)) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4->mapclassify->-r data/requirements.txt (line 5)) (3.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->folium->-r data/requirements.txt (line 3)) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->folium->-r data/requirements.txt (line 3)) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->folium->-r data/requirements.txt (line 3)) (2025.8.3)
Collecting pyrate-limiter<3.0 (from requests-ratelimiter->bdcdata->-r data/requirements.txt (line 1))
  Downloading pyrate_limiter-2.10.0-py3-none-any.whl.metadata (15 kB)
Downloading bdcdata-0.0.10-py3-none-any.whl (6.0 kB)
Downloading h3pandas-0.3.0-py3-none-any.whl (53 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.3/53.3 kB 2.1 MB/s eta 0:00:00
Downloading mapclassify-2.10.0-py3-none-any.whl (882 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 882.2/882.2 kB 18.4 MB/s eta 0:00:00
Downloading pygris-0.2.0-py3-none-any.whl (57 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 4.1 MB/s eta 0:00:00
Downloading ndtguide-0.1.1-py3-none-any.whl (5.9 kB)
Downloading awscli-1.42.33-py3-none-any.whl (4.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 81.6 MB/s eta 0:00:00
Downloading botocore-1.40.33-py3-none-any.whl (14.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 92.9 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading docutils-0.19-py3-none-any.whl (570 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 570.5/570.5 kB 31.1 MB/s eta 0:00:00
Downloading h3-4.3.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 51.3 MB/s eta 0:00:00
Downloading rsa-4.7.2-py3-none-any.whl (34 kB)
Downloading s3transfer-0.14.0-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.7/85.7 kB 5.8 MB/s eta 0:00:00
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading requests_ratelimiter-0.7.0-py3-none-any.whl (9.3 kB)
Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)
Downloading pyrate_limiter-2.10.0-py3-none-any.whl (16 kB)
Installing collected packages: ndtguide, appdirs, rsa, pyrate-limiter, jmespath, h3, docutils, colorama, requests-ratelimiter, botocore, s3transfer, mapclassify, bdcdata, pygris, h3pandas, awscli
  Attempting uninstall: rsa
    Found existing installation: rsa 4.9.1
    Uninstalling rsa-4.9.1:
      Successfully uninstalled rsa-4.9.1
  Attempting uninstall: docutils
    Found existing installation: docutils 0.21.2
    Uninstalling docutils-0.21.2:
      Successfully uninstalled docutils-0.21.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sphinx 8.2.3 requires docutils<0.22,>=0.20, but you have docutils 0.19 which is incompatible.
Successfully installed appdirs-1.4.4 awscli-1.42.33 bdcdata-0.0.10 botocore-1.40.33 colorama-0.4.6 docutils-0.19 h3-4.3.1 h3pandas-0.3.0 jmespath-1.0.1 mapclassify-2.10.0 ndtguide-0.1.1 pygris-0.2.0 pyrate-limiter-2.10.0 requests-ratelimiter-0.7.0 rsa-4.7.2 s3transfer-0.14.0

Setup API Keys first

In [3]:
import os, pathlib, h3pandas, pygris
from google.colab import userdata
from ndtguide import NDTGuide
import pandas as pd
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt
os.environ["BDC_USERNAME"] = userdata.get('bdc_email')
os.environ["BDC_API_KEY"] = userdata.get('bdc_hash')

In [4]:
import bdcdata

{'User-Agent': 'python-bdc', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'hash_value': '2y/1NvvejDWWuZt4vXrkL9LQ4QNeprc1qPzW8w8Zvz0=', 'username': 'nick.pappin@wsu.edu'}
DEBUG:bdcdata:{'User-Agent': 'python-bdc', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'hash_value': '2y/1NvvejDWWuZt4vXrkL9LQ4QNeprc1qPzW8w8Zvz0=', 'username': 'nick.pappin@wsu.edu'}
Session created.
INFO:bdcdata:Session created.
Collecting metadata...
INFO:bdcdata:Collecting metadata...
{'data': [{'data_type': 'availability', 'as_of_date': '2022-06-30'}, {'data_type': 'availability', 'as_of_date': '2022-12-31'}, {'data_type': 'availability', 'as_of_date': '2023-06-30'}, {'data_type': 'availability', 'as_of_date': '2023-12-31'}, {'data_type': 'availability', 'as_of_date': '2024-06-30'}, {'data_type': 'availability', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2022-11-30'}, {'data_type': 'challenge', 'as_of_date': '2022-12-31'}, {'data_type': 'challenge', 'as_of_date': '2023-01-31'}, {'data_type': 'challenge', 'as_of_date': '2023-02-28'}, {'data_type': 'challenge', 'as_of_date': '2023-03-31'}, {'data_type': 'challenge', 'as_of_date': '2023-04-30'}, {'data_type': 'challenge', 'as_of_date': '2023-05-31'}, {'data_type': 'challenge', 'as_of_date': '2023-06-30'}, {'data_type': 'challenge', 'as_of_date': '2023-07-31'}, {'data_type': 'challenge', 'as_of_date': '2023-08-31'}, {'data_type': 'challenge', 'as_of_date': '2023-09-30'}, {'data_type': 'challenge', 'as_of_date': '2023-10-31'}, {'data_type': 'challenge', 'as_of_date': '2023-11-30'}, {'data_type': 'challenge', 'as_of_date': '2023-12-31'}, {'data_type': 'challenge', 'as_of_date': '2024-01-31'}, {'data_type': 'challenge', 'as_of_date': '2024-02-29'}, {'data_type': 'challenge', 'as_of_date': '2024-03-31'}, {'data_type': 'challenge', 'as_of_date': '2024-04-30'}, {'data_type': 'challenge', 'as_of_date': '2024-05-31'}, {'data_type': 'challenge', 'as_of_date': '2024-06-30'}, {'data_type': 'challenge', 'as_of_date': '2024-07-31'}, {'data_type': 'challenge', 'as_of_date': '2024-08-31'}, {'data_type': 'challenge', 'as_of_date': '2024-09-30'}, {'data_type': 'challenge', 'as_of_date': '2024-10-31'}, {'data_type': 'challenge', 'as_of_date': '2024-11-30'}, {'data_type': 'challenge', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2025-01-31'}, {'data_type': 'challenge', 'as_of_date': '2025-02-28'}, {'data_type': 'challenge', 'as_of_date': '2025-03-31'}, {'data_type': 'challenge', 'as_of_date': '2025-04-30'}, {'data_type': 'challenge', 'as_of_date': '2025-05-31'}, {'data_type': 'challenge', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2025-07-31'}, {'data_type': 'challenge', 'as_of_date': '2025-08-31'}], 'result_count': 40, 'status_code': 200, 'message': None, 'status': 'successful', 'request_date': '2025-09-18T03:14:27.436Z'}
DEBUG:bdcdata:{'data': [{'data_type': 'availability', 'as_of_date': '2022-06-30'}, {'data_type': 'availability', 'as_of_date': '2022-12-31'}, {'data_type': 'availability', 'as_of_date': '2023-06-30'}, {'data_type': 'availability', 'as_of_date': '2023-12-31'}, {'data_type': 'availability', 'as_of_date': '2024-06-30'}, {'data_type': 'availability', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2022-11-30'}, {'data_type': 'challenge', 'as_of_date': '2022-12-31'}, {'data_type': 'challenge', 'as_of_date': '2023-01-31'}, {'data_type': 'challenge', 'as_of_date': '2023-02-28'}, {'data_type': 'challenge', 'as_of_date': '2023-03-31'}, {'data_type': 'challenge', 'as_of_date': '2023-04-30'}, {'data_type': 'challenge', 'as_of_date': '2023-05-31'}, {'data_type': 'challenge', 'as_of_date': '2023-06-30'}, {'data_type': 'challenge', 'as_of_date': '2023-07-31'}, {'data_type': 'challenge', 'as_of_date': '2023-08-31'}, {'data_type': 'challenge', 'as_of_date': '2023-09-30'}, {'data_type': 'challenge', 'as_of_date': '2023-10-31'}, {'data_type': 'challenge', 'as_of_date': '2023-11-30'}, {'data_type': 'challenge', 'as_of_date': '2023-12-31'}, {'data_type': 'challenge', 'as_of_date': '2024-01-31'}, {'data_type': 'challenge', 'as_of_date': '2024-02-29'}, {'data_type': 'challenge', 'as_of_date': '2024-03-31'}, {'data_type': 'challenge', 'as_of_date': '2024-04-30'}, {'data_type': 'challenge', 'as_of_date': '2024-05-31'}, {'data_type': 'challenge', 'as_of_date': '2024-06-30'}, {'data_type': 'challenge', 'as_of_date': '2024-07-31'}, {'data_type': 'challenge', 'as_of_date': '2024-08-31'}, {'data_type': 'challenge', 'as_of_date': '2024-09-30'}, {'data_type': 'challenge', 'as_of_date': '2024-10-31'}, {'data_type': 'challenge', 'as_of_date': '2024-11-30'}, {'data_type': 'challenge', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2025-01-31'}, {'data_type': 'challenge', 'as_of_date': '2025-02-28'}, {'data_type': 'challenge', 'as_of_date': '2025-03-31'}, {'data_type': 'challenge', 'as_of_date': '2025-04-30'}, {'data_type': 'challenge', 'as_of_date': '2025-05-31'}, {'data_type': 'challenge', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2025-07-31'}, {'data_type': 'challenge', 'as_of_date': '2025-08-31'}], 'result_count': 40, 'status_code': 200, 'message': None, 'status': 'successful', 'request_date': '2025-09-18T03:14:27.436Z'}
{'data': [{'data_type': 'availability', 'as_of_date': '2022-06-30'}, {'data_type': 'availability', 'as_of_date': '2022-12-31'}, {'data_type': 'availability', 'as_of_date': '2023-06-30'}, {'data_type': 'availability', 'as_of_date': '2023-12-31'}, {'data_type': 'availability', 'as_of_date': '2024-06-30'}, {'data_type': 'availability', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2022-11-30'}, {'data_type': 'challenge', 'as_of_date': '2022-12-31'}, {'data_type': 'challenge', 'as_of_date': '2023-01-31'}, {'data_type': 'challenge', 'as_of_date': '2023-02-28'}, {'data_type': 'challenge', 'as_of_date': '2023-03-31'}, {'data_type': 'challenge', 'as_of_date': '2023-04-30'}, {'data_type': 'challenge', 'as_of_date': '2023-05-31'}, {'data_type': 'challenge', 'as_of_date': '2023-06-30'}, {'data_type': 'challenge', 'as_of_date': '2023-07-31'}, {'data_type': 'challenge', 'as_of_date': '2023-08-31'}, {'data_type': 'challenge', 'as_of_date': '2023-09-30'}, {'data_type': 'challenge', 'as_of_date': '2023-10-31'}, {'data_type': 'challenge', 'as_of_date': '2023-11-30'}, {'data_type': 'challenge', 'as_of_date': '2023-12-31'}, {'data_type': 'challenge', 'as_of_date': '2024-01-31'}, {'data_type': 'challenge', 'as_of_date': '2024-02-29'}, {'data_type': 'challenge', 'as_of_date': '2024-03-31'}, {'data_type': 'challenge', 'as_of_date': '2024-04-30'}, {'data_type': 'challenge', 'as_of_date': '2024-05-31'}, {'data_type': 'challenge', 'as_of_date': '2024-06-30'}, {'data_type': 'challenge', 'as_of_date': '2024-07-31'}, {'data_type': 'challenge', 'as_of_date': '2024-08-31'}, {'data_type': 'challenge', 'as_of_date': '2024-09-30'}, {'data_type': 'challenge', 'as_of_date': '2024-10-31'}, {'data_type': 'challenge', 'as_of_date': '2024-11-30'}, {'data_type': 'challenge', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2025-01-31'}, {'data_type': 'challenge', 'as_of_date': '2025-02-28'}, {'data_type': 'challenge', 'as_of_date': '2025-03-31'}, {'data_type': 'challenge', 'as_of_date': '2025-04-30'}, {'data_type': 'challenge', 'as_of_date': '2025-05-31'}, {'data_type': 'challenge', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2025-07-31'}, {'data_type': 'challenge', 'as_of_date': '2025-08-31'}], 'result_count': 40, 'status_code': 200, 'message': None, 'status': 'successful', 'request_date': '2025-09-18T03:14:27.436Z'}
INFO:bdcdata:{'data': [{'data_type': 'availability', 'as_of_date': '2022-06-30'}, {'data_type': 'availability', 'as_of_date': '2022-12-31'}, {'data_type': 'availability', 'as_of_date': '2023-06-30'}, {'data_type': 'availability', 'as_of_date': '2023-12-31'}, {'data_type': 'availability', 'as_of_date': '2024-06-30'}, {'data_type': 'availability', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2022-11-30'}, {'data_type': 'challenge', 'as_of_date': '2022-12-31'}, {'data_type': 'challenge', 'as_of_date': '2023-01-31'}, {'data_type': 'challenge', 'as_of_date': '2023-02-28'}, {'data_type': 'challenge', 'as_of_date': '2023-03-31'}, {'data_type': 'challenge', 'as_of_date': '2023-04-30'}, {'data_type': 'challenge', 'as_of_date': '2023-05-31'}, {'data_type': 'challenge', 'as_of_date': '2023-06-30'}, {'data_type': 'challenge', 'as_of_date': '2023-07-31'}, {'data_type': 'challenge', 'as_of_date': '2023-08-31'}, {'data_type': 'challenge', 'as_of_date': '2023-09-30'}, {'data_type': 'challenge', 'as_of_date': '2023-10-31'}, {'data_type': 'challenge', 'as_of_date': '2023-11-30'}, {'data_type': 'challenge', 'as_of_date': '2023-12-31'}, {'data_type': 'challenge', 'as_of_date': '2024-01-31'}, {'data_type': 'challenge', 'as_of_date': '2024-02-29'}, {'data_type': 'challenge', 'as_of_date': '2024-03-31'}, {'data_type': 'challenge', 'as_of_date': '2024-04-30'}, {'data_type': 'challenge', 'as_of_date': '2024-05-31'}, {'data_type': 'challenge', 'as_of_date': '2024-06-30'}, {'data_type': 'challenge', 'as_of_date': '2024-07-31'}, {'data_type': 'challenge', 'as_of_date': '2024-08-31'}, {'data_type': 'challenge', 'as_of_date': '2024-09-30'}, {'data_type': 'challenge', 'as_of_date': '2024-10-31'}, {'data_type': 'challenge', 'as_of_date': '2024-11-30'}, {'data_type': 'challenge', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2025-01-31'}, {'data_type': 'challenge', 'as_of_date': '2025-02-28'}, {'data_type': 'challenge', 'as_of_date': '2025-03-31'}, {'data_type': 'challenge', 'as_of_date': '2025-04-30'}, {'data_type': 'challenge', 'as_of_date': '2025-05-31'}, {'data_type': 'challenge', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2025-07-31'}, {'data_type': 'challenge', 'as_of_date': '2025-08-31'}], 'result_count': 40, 'status_code': 200, 'message': None, 'status': 'successful', 'request_date': '2025-09-18T03:14:27.436Z'}
[{'data_type': 'availability', 'as_of_date': '2022-06-30'}, {'data_type': 'availability', 'as_of_date': '2022-12-31'}, {'data_type': 'availability', 'as_of_date': '2023-06-30'}, {'data_type': 'availability', 'as_of_date': '2023-12-31'}, {'data_type': 'availability', 'as_of_date': '2024-06-30'}, {'data_type': 'availability', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2022-11-30'}, {'data_type': 'challenge', 'as_of_date': '2022-12-31'}, {'data_type': 'challenge', 'as_of_date': '2023-01-31'}, {'data_type': 'challenge', 'as_of_date': '2023-02-28'}, {'data_type': 'challenge', 'as_of_date': '2023-03-31'}, {'data_type': 'challenge', 'as_of_date': '2023-04-30'}, {'data_type': 'challenge', 'as_of_date': '2023-05-31'}, {'data_type': 'challenge', 'as_of_date': '2023-06-30'}, {'data_type': 'challenge', 'as_of_date': '2023-07-31'}, {'data_type': 'challenge', 'as_of_date': '2023-08-31'}, {'data_type': 'challenge', 'as_of_date': '2023-09-30'}, {'data_type': 'challenge', 'as_of_date': '2023-10-31'}, {'data_type': 'challenge', 'as_of_date': '2023-11-30'}, {'data_type': 'challenge', 'as_of_date': '2023-12-31'}, {'data_type': 'challenge', 'as_of_date': '2024-01-31'}, {'data_type': 'challenge', 'as_of_date': '2024-02-29'}, {'data_type': 'challenge', 'as_of_date': '2024-03-31'}, {'data_type': 'challenge', 'as_of_date': '2024-04-30'}, {'data_type': 'challenge', 'as_of_date': '2024-05-31'}, {'data_type': 'challenge', 'as_of_date': '2024-06-30'}, {'data_type': 'challenge', 'as_of_date': '2024-07-31'}, {'data_type': 'challenge', 'as_of_date': '2024-08-31'}, {'data_type': 'challenge', 'as_of_date': '2024-09-30'}, {'data_type': 'challenge', 'as_of_date': '2024-10-31'}, {'data_type': 'challenge', 'as_of_date': '2024-11-30'}, {'data_type': 'challenge', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2025-01-31'}, {'data_type': 'challenge', 'as_of_date': '2025-02-28'}, {'data_type': 'challenge', 'as_of_date': '2025-03-31'}, {'data_type': 'challenge', 'as_of_date': '2025-04-30'}, {'data_type': 'challenge', 'as_of_date': '2025-05-31'}, {'data_type': 'challenge', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2025-07-31'}, {'data_type': 'challenge', 'as_of_date': '2025-08-31'}]
DEBUG:bdcdata:[{'data_type': 'availability', 'as_of_date': '2022-06-30'}, {'data_type': 'availability', 'as_of_date': '2022-12-31'}, {'data_type': 'availability', 'as_of_date': '2023-06-30'}, {'data_type': 'availability', 'as_of_date': '2023-12-31'}, {'data_type': 'availability', 'as_of_date': '2024-06-30'}, {'data_type': 'availability', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2022-11-30'}, {'data_type': 'challenge', 'as_of_date': '2022-12-31'}, {'data_type': 'challenge', 'as_of_date': '2023-01-31'}, {'data_type': 'challenge', 'as_of_date': '2023-02-28'}, {'data_type': 'challenge', 'as_of_date': '2023-03-31'}, {'data_type': 'challenge', 'as_of_date': '2023-04-30'}, {'data_type': 'challenge', 'as_of_date': '2023-05-31'}, {'data_type': 'challenge', 'as_of_date': '2023-06-30'}, {'data_type': 'challenge', 'as_of_date': '2023-07-31'}, {'data_type': 'challenge', 'as_of_date': '2023-08-31'}, {'data_type': 'challenge', 'as_of_date': '2023-09-30'}, {'data_type': 'challenge', 'as_of_date': '2023-10-31'}, {'data_type': 'challenge', 'as_of_date': '2023-11-30'}, {'data_type': 'challenge', 'as_of_date': '2023-12-31'}, {'data_type': 'challenge', 'as_of_date': '2024-01-31'}, {'data_type': 'challenge', 'as_of_date': '2024-02-29'}, {'data_type': 'challenge', 'as_of_date': '2024-03-31'}, {'data_type': 'challenge', 'as_of_date': '2024-04-30'}, {'data_type': 'challenge', 'as_of_date': '2024-05-31'}, {'data_type': 'challenge', 'as_of_date': '2024-06-30'}, {'data_type': 'challenge', 'as_of_date': '2024-07-31'}, {'data_type': 'challenge', 'as_of_date': '2024-08-31'}, {'data_type': 'challenge', 'as_of_date': '2024-09-30'}, {'data_type': 'challenge', 'as_of_date': '2024-10-31'}, {'data_type': 'challenge', 'as_of_date': '2024-11-30'}, {'data_type': 'challenge', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2025-01-31'}, {'data_type': 'challenge', 'as_of_date': '2025-02-28'}, {'data_type': 'challenge', 'as_of_date': '2025-03-31'}, {'data_type': 'challenge', 'as_of_date': '2025-04-30'}, {'data_type': 'challenge', 'as_of_date': '2025-05-31'}, {'data_type': 'challenge', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2025-07-31'}, {'data_type': 'challenge', 'as_of_date': '2025-08-31'}]
Metadata collected.
INFO:bdcdata:Metadata collected.
Data type: availability
DEBUG:bdcdata:Data type: availability
{'data_type': 'availability', 'as_of_date': '2022-06-30'}
DEBUG:bdcdata:{'data_type': 'availability', 'as_of_date': '2022-06-30'}
Data type: availability
DEBUG:bdcdata:Data type: availability
{'data_type': 'availability', 'as_of_date': '2022-12-31'}
DEBUG:bdcdata:{'data_type': 'availability', 'as_of_date': '2022-12-31'}
Data type: availability
DEBUG:bdcdata:Data type: availability
{'data_type': 'availability', 'as_of_date': '2023-06-30'}
DEBUG:bdcdata:{'data_type': 'availability', 'as_of_date': '2023-06-30'}
Data type: availability
DEBUG:bdcdata:Data type: availability
{'data_type': 'availability', 'as_of_date': '2023-12-31'}
DEBUG:bdcdata:{'data_type': 'availability', 'as_of_date': '2023-12-31'}
Data type: availability
DEBUG:bdcdata:Data type: availability
{'data_type': 'availability', 'as_of_date': '2024-06-30'}
DEBUG:bdcdata:{'data_type': 'availability', 'as_of_date': '2024-06-30'}
Data type: availability
DEBUG:bdcdata:Data type: availability
{'data_type': 'availability', 'as_of_date': '2024-12-31'}
DEBUG:bdcdata:{'data_type': 'availability', 'as_of_date': '2024-12-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2022-11-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2022-11-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2022-12-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2022-12-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-01-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-01-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-02-28'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-02-28'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-03-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-03-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-04-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-04-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-05-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-05-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-06-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-06-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-07-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-07-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-08-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-08-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-09-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-09-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-10-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-10-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-11-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-11-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-12-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-12-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-01-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-01-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-02-29'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-02-29'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-03-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-03-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-04-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-04-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-05-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-05-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-06-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-06-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-07-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-07-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-08-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-08-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-09-30'}

## Pull data

In [5]:
waData = bdcdata.availability.fixed(states=[53], technology='fixed', release=['2024-12-31'], cache=True)

Collecting availability...
INFO:bdcdata:Collecting availability...
State: [53]
DEBUG:bdcdata:State: [53]
Technology: fixed
DEBUG:bdcdata:Technology: fixed
Release: ['2024-12-31']
DEBUG:bdcdata:Release: ['2024-12-31']
State: Washington({'file_id': 1236019, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '10', 'technology_code_desc': 'Copper', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_Copper_fixed_broadband_D24_16sep2025', 'record_count': '1102663'})), Technology: 10, Release: 2024-12-31
DEBUG:bdcdata:State: Washington({'file_id': 1236019, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '10', 'technology_code_desc': 'Copper', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_Copper_fixed_broadband_D24_16sep2025', 'record_count': '1102663'})), Technology: 10, Release: 2024-12-31
State: Washington({'file_id': 1236073, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '40', 'technology_code_desc': 'Cable', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_Cable_fixed_broadband_D24_16sep2025', 'record_count': '2296179'})), Technology: 40, Release: 2024-12-31
DEBUG:bdcdata:State: Washington({'file_id': 1236073, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '40', 'technology_code_desc': 'Cable', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_Cable_fixed_broadband_D24_16sep2025', 'record_count': '2296179'})), Technology: 40, Release: 2024-12-31
State: Washington({'file_id': 1236129, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '50', 'technology_code_desc': 'Fiber to the Premises', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_FibertothePremises_fixed_broadband_D24_16sep2025', 'record_count': '1094954'})), Technology: 50, Release: 2024-12-31
DEBUG:bdcdata:State: Washington({'file_id': 1236129, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '50', 'technology_code_desc': 'Fiber to the Premises', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_FibertothePremises_fixed_broadband_D24_16sep2025', 'record_count': '1094954'})), Technology: 50, Release: 2024-12-31
State: Washington({'file_id': 1236185, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '60', 'technology_code_desc': 'GSO Satellite', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_GSOSatellite_fixed_broadband_D24_16sep2025', 'record_count': '7707217'})), Technology: 60, Release: 2024-12-31
DEBUG:bdcdata:State: Washington({'file_id': 1236185, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '60', 'technology_code_desc': 'GSO Satellite', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_GSOSatellite_fixed_broadband_D24_16sep2025', 'record_count': '7707217'})), Technology: 60, Release: 2024-12-31
State: Washington({'file_id': 1236238, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '61', 'technology_code_desc': 'NGSO Satellite', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_NGSOSatellite_fixed_broadband_D24_16sep2025', 'record_count': '2565799'})), Technology: 61, Release: 2024-12-31
DEBUG:bdcdata:State: Washington({'file_id': 1236238, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '61', 'technology_code_desc': 'NGSO Satellite', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_NGSOSatellite_fixed_broadband_D24_16sep2025', 'record_count': '2565799'})), Technology: 61, Release: 2024-12-31
State: Washington({'file_id': 1236293, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '70', 'technology_code_desc': 'Unlicensed Fixed Wireless', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_UnlicensedFixedWireless_fixed_broadband_D24_16sep2025', 'record_count': '1354322'})), Technology: 70, Release: 2024-12-31
DEBUG:bdcdata:State: Washington({'file_id': 1236293, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '70', 'technology_code_desc': 'Unlicensed Fixed Wireless', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_UnlicensedFixedWireless_fixed_broadband_D24_16sep2025', 'record_count': '1354322'})), Technology: 70, Release: 2024-12-31
State: Washington({'file_id': 1236348, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '71', 'technology_code_desc': 'Licensed Fixed Wireless', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_LicensedFixedWireless_fixed_broadband_D24_16sep2025', 'record_count': '3607462'})), Technology: 71, Release: 2024-12-31
DEBUG:bdcdata:State: Washington({'file_id': 1236348, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '71', 'technology_code_desc': 'Licensed Fixed Wireless', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_LicensedFixedWireless_fixed_broadband_D24_16sep2025', 'record_count': '3607462'})), Technology: 71, Release: 2024-12-31
State: Washington({'file_id': 1236398, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '72', 'technology_code_desc': 'LBR Fixed Wireless', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_LBRFixedWireless_fixed_broadband_D24_16sep2025', 'record_count': '165041'})), Technology: 72, Release: 2024-12-31
DEBUG:bdcdata:State: Washington({'file_id': 1236398, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '72', 'technology_code_desc': 'LBR Fixed Wireless', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_LBRFixedWireless_fixed_broadband_D24_16sep2025', 'record_count': '165041'})), Technology: 72, Release: 2024-12-31
State: ['53'], Technology: ['0', '10', '40', '50', '60', '61', '70', '71', '72'], Release: ['2024-12-31']
DEBUG:bdcdata:State: ['53'], Technology: ['0', '10', '40', '50', '60', '61', '70', '71', '72'], Release: ['2024-12-31']

In [6]:
waData.sample(n=20)

,frn,provider_id,brand_name,location_id,technology,max_advertised_download_speed,max_advertised_upload_speed,low_latency,business_residential_code,state_usps,block_geoid,h3_res8_id,release
19630479,0005937974,130077,AT&T,1342698754,71,10,1,True,B,WA,530630104032051,8812db7117fffff,2024-12-31
14944806,0031764293,420173,Ziply Wireless,1042974517,70,50,10,True,X,WA,530439603003084,88288b6097fffff,2024-12-31
129792,0018626853,130228,CenturyLink,1073187496,10,40,3,True,X,WA,530350907003003,8828d546c7fffff,2024-12-31
3854743,0029765211,420173,Ziply Fiber,1337166073,50,6000,6000,True,X,WA,530610528071010,8828d0a523fffff,2024-12-31
15629627,0031764293,420173,Ziply Wireless,1342630125,70,25,5,True,X,WA,530630107011015,8812db0d13fffff,2024-12-31
15040513,0015592397,131497,Wired or Wireless Inc,1342684774,70,30,10,True,X,WA,530630013002036,8812db0d95fffff,2024-12-31
12079664,0012369286,130627,HughesNet,1330392089,60,100,5,False,X,WA,530530719012012,8828d5d76dfffff,2024-12-31
10330879,0012369286,130627,HughesNet,1342546969,60,100,5,False,X,WA,530630119001002,8812db39cdfffff,2024-12-31
9793340,0004963088,290111,Viasat Inc,1073232400,60,100,4,False,B,WA,530350901022006,8828d57a31fffff,2024-12-31
7878713,0012369286,130627,HughesNet,1349363698,60,100,5,False,X,WA,530110428002005,8828f001b7fffff,2024-12-31
14921297,0023973480,290093,Pogozone powered by Neubeam,1310136534,70,40,7,True,X,WA,530730003011006,8828d17b53fffff,2024-12-31
11177880,0012369286,130627,HughesNet,1366615806,60,100,5,False,X,WA,530330323233004,8828d54a13fffff,2024-12-31
8598965,0004963088,290111,Viasat Inc,1366627758,60,100,3,False,R,WA,530330087002006,8828d54211fffff,2024-12-31
10702455,0012369286,130627,HughesNet,1313002836,60,100,5,False,X,WA,530579403022015,8828d11b17fffff,2024-12-31
18570892,0018506568,131425,Verizon,1366957687,71,300,20,True,R,WA,530330274002002,8828d552c7fffff,2024-12-31
17039937,0005937974,130077,AT&T,1330403440,71,25,3,True,R,WA,530530633022014,8828d5d199fffff,2024-12-31
4947249,0004963088,290111,Viasat Inc,1110491230,60,50,3,False,R,WA,530250103002037,8828d6db09fffff,2024-12-31
11966023,0012369286,130627,HughesNet,1349303026,60,100,5,False,X,WA,530110414003005,8828f00b6bfffff,2024-12-31
6222429,0012369286,130627,HughesNet,1367028333,60,100,5,False,X,WA,530330216002007,8828d54e27fffff,2024-12-31
17808113,0006945950,130403,T-Mobile,1366473961,71,100,20,True,X,WA,530330317073000,8828d5c955fffff,2024-12-31

In [7]:
waData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19893637 entries, 0 to 19893636
Data columns (total 13 columns):
 #   Column                         Dtype
---  ------                         -----
 0   frn                            object
 1   provider_id                    UInt32
 2   brand_name                     object
 3   location_id                    UInt32
 4   technology                     UInt16
 5   max_advertised_download_speed  UInt32
 6   max_advertised_upload_speed    UInt32
 7   low_latency                    boolean
 8   business_residential_code      string[pyarrow]
 9   state_usps                     category
 10  block_geoid                    object
 11  h3_res8_id                     object
 12  release                        object
dtypes: UInt16(1), UInt32(4), boolean(1), category(1), object(5), string[pyarrow](1)
memory usage: 1.3+ GB

In [8]:
locationLookup = waData[['location_id', 'block_geoid', 'h3_res8_id']].drop_duplicates(ignore_index=True)

In [9]:
locationLookup

         location_id      block_geoid       h3_res8_id
0         1027407142  530519705001008  8812db8c59fffff
1         1121311109  530179508002000  8828d68111fffff
2         1122544844  530199702002003  8812da8343fffff
3         1296237355  530079604001044  8828d60c6dfffff
4         1296248370  530299710001051  8828d1d5d1fffff
...              ...              ...              ...
2566302   1564065810  530319503013007  8828d56069fffff
2566303   1564114121  530670117202021  8828d59369fffff
2566304   1564174977  530079603021002  8828d6081bfffff
2566305   1564299037  530459604031000  8828d51231fffff
2566306   1349409498  530110405043001  8828f07365fffff

[2566307 rows x 3 columns]

## Census Data

In [ ]:
waBlocks = pygris.blocks(state='53', cache=True)
waBlockGroups = pygris.block_groups(state='53', cache=True)
waTracts = pygris.tracts(state='53', cache=True)
waCounties = pygris.counties(state='53', cache=True)
waState = pygris.states(cache=True)
waState = waState[waState.NAME == 'Washington']

Using the default year of 2024
HTTP download failed, trying FTP as fallback...
Downloading tl_2024_53_tabblock20.zip from Census FTP...

In [ ]:
waState.plot(edgecolor='black', lw=3)

In [ ]:
waCounties.plot(edgecolor='black', lw=3)

In [ ]:
waTracts

In [ ]:
waTracts.plot(edgecolor='black', lw=.2)
waTracts[waTracts.COUNTYFP == '075'].plot(edgecolor='black', lw=1)

In [ ]:
waBlockGroups.plot()
waBlockGroups[waBlockGroups.COUNTYFP == '075'].plot(edgecolor='black', lw=.2)

In [ ]:
# waBlocks.plot()
waBlocks[waBlocks.COUNTYFP20 == '075'].explore(tiles="CartoDB Positron")

In [ ]:
waBlocks.sample(n=100)

In [ ]:
blockLocations = locationLookup.block_geoid.value_counts().reset_index()

In [ ]:
blockLocations.block_geoid.str[0:10]

In [ ]:
blockLocations = blockLocations.merge(waBlocks, how='left', left_on='block_geoid', right_on='GEOID20')

In [ ]:
blockLocations

In [ ]:
blockLocations = gpd.GeoDataFrame(blockLocations)

In [ ]:
fig, ax2 = plt.subplots(figsize=(16, 16))
blockLocations.plot(ax = ax2, column='count', scheme='FisherJenks', legend=True)
fig.show()

In [ ]:
plt.close(fig)

In [ ]:
blockLocations['countPopNorm'] = blockLocations['count'] / blockLocations.POP20.replace(0, np.nan)
blockLocations['countHousingNorm'] = blockLocations['count'] / blockLocations.HOUSING20.replace(0, np.nan)

In [ ]:
blockLocations.sample(n=5)

In [ ]:
int(blockLocations.shape[0]*.1)

In [ ]:
fig, ax2 = plt.subplots(figsize=(16, 16))
num = int(blockLocations.shape[0]*.01)
waState.plot(ax=ax2, facecolor='none', edgecolor='black', lw=3)
blockLocations.nlargest(num, 'countPopNorm').plot(ax = ax2, column='countPopNorm', scheme='FisherJenks', legend=True)
fig.show()

In [ ]:
plt.close(fig)

In [ ]:
blockLocations.nlargest(100, 'countPopNorm')[0]

In [ ]:
fig, ax2 = plt.subplots(figsize=(16, 16))
blockLocations.plot(ax = ax2, column='countHousingNorm', scheme='FisherJenks', legend=True)

## H3 Data

In [ ]:
fpLocations = pd.read_csv(pathlib.Path('data', 'fp_locations.csv'))

In [ ]:
fpLocations.drop_duplicates()

In [ ]:
locations = fpLocations[['location_id', 'technology']].merge(locationLookup, how='left', on='location_id')

In [ ]:
locations.shape

In [ ]:
locations.drop_duplicates()

In [ ]:
pivoted = locations[['h3_res8_id', 'technology', 'location_id']].pivot_table(index='h3_res8_id', columns='technology', values='location_id', aggfunc='count', fill_value=0, )
pivoted.columns = pivoted.columns.astype(str)

In [ ]:
pivoted.to_excel('test.xlsx')

In [ ]:
pivoted.info()

In [ ]:
pivoted['70s'] = pivoted.loc[:, "70"] + pivoted.loc[:, "71"] + pivoted.loc[:, "72"]

In [ ]:
pivoted['max'] = pivoted[["50", "70s", "61"]].idxmax(axis=1)

In [ ]:
techHash = {
    '50': 'Fiber',
    '61': 'LEO',
    '70': 'ULFW',
    '71': 'LFW',
    '72': 'LBRW',
    '70s': 'Wireless'
}

In [ ]:
pivoted.rename(columns=techHash, inplace=True)

In [ ]:
pivoted

In [ ]:
gpd.GeoDataFrame(pivoted.h3.h3_to_geo_boundary()).explore(column='max', categorical=True, tiles="CartoDB dark_matter").save("h3.html")

## NYLS Analysis

Let's start by looking at the article and the data they used.

* https://broadbandexpanded.com/posts/botblocations
* https://broadbandexpanded-my.sharepoint.com/:x:/p/alex/EUZMR4YBJSNGlV0KVDzTgp0B5D6M_Xti8QaUhregXhxToA?rtime=EBI1LAnv3Ug&nav=MTVfezFBMUU2NzczLUExNjktNEM4RC05N0FBLUNBRkM1RTAyNEM5NX0


Mike Conlow data

https://mikeconlow.substack.com/p/new-national-broadband-map-update-c4d

Lets look at summary data and compare it across to the numbers provided
State data

https://broadbandmap.fcc.gov

In [ ]:
waNYLS = bdcdata.availability.fixed(states='53', technology='fixed', cache=True, release=['2022-12-31', '2024-06-30'])
# waNYLS = bdcdata.availability.fixed(states='53', technology='fixed', cache=True, release=['2022-12-31', '2024-06-30', '2024-12-31'])
# waNYLS = bdcdata.availability.fixed(states='53', technology='fixed', cache=True, release=['2024-06-30', '2024-12-31'])

In [ ]:
tech=[10, 40, 50, 70, 71, 72]

In [ ]:
d22Summary = pd.read_csv(pathlib.Path('cache', 'bdc_us_fixed_broadband_summary_by_geography_D22_02may2025.csv'))
j24Summary = pd.read_csv(pathlib.Path('cache', 'bdc_us_fixed_broadband_summary_by_geography_J24_01sep2025.csv'))

In [ ]:
d22Summary

In [ ]:
d22Summary[(d22Summary.geography_type == 'State') & (d22Summary.geography_desc == 'Washington') & (d22Summary.area_data_type == 'Total')]

In [ ]:
j24Summary[(j24Summary.geography_type == 'State') & (j24Summary.geography_desc == 'Washington') & (j24Summary.area_data_type == 'Total')]

In [ ]:
# print(f'D22 Un/underserved units: {int(3514723-(3514723*0.8954)):,}')
print(f'D22 Un/underserved units: {int(3514723-(3514723*0.9226)):,}')
print(f'J24 Un/underserved units: {int(3658756-(3658756*0.938259)):,}')
print(f'J24 Un/underserved units (BotB): {int(3658756-(3658756*0.954147	)):,}')

In [ ]:
waNYLS.sample(n=10)

In [ ]:
d22 = waNYLS[waNYLS.release == "2022-12-31"]

In [ ]:
d22Bsls = pd.DataFrame(d22.location_id.drop_duplicates(ignore_index=True))

In [ ]:
d22Bsls['status'] = 'Unserved'

In [ ]:
d22Bsls

In [ ]:
d22UnderservedIds = d22[(d22.max_advertised_download_speed >= 25) & (d22.max_advertised_upload_speed >= 3) & (d22.technology.isin(tech))] \
  .location_id.drop_duplicates() \
  .reset_index(drop=True).to_list()
d22Bsls.loc[d22Bsls.location_id.isin(d22UnderservedIds), 'status'] = 'Underserved'
d22ServedIds = d22[(d22.max_advertised_download_speed >= 100) & (d22.max_advertised_upload_speed >= 20) & (d22.technology.isin(tech))] \
  .location_id.drop_duplicates() \
  .reset_index(drop=True).to_list()
d22Bsls.loc[d22Bsls.location_id.isin(d22ServedIds), 'status'] = 'Served'

In [ ]:
d22Bsls.status.value_counts()

In [ ]:
j24 = waNYLS[waNYLS.release == "2024-06-30"]

In [ ]:
j24Bsls = pd.DataFrame(j24.location_id.drop_duplicates(ignore_index=True))
j24Bsls['status'] = 'Unserved'

In [ ]:
j24UnderservedIds = j24[(j24.max_advertised_download_speed >= 25) & (j24.max_advertised_upload_speed >= 3) & (j24.technology.isin(tech))] \
  .location_id.drop_duplicates() \
  .reset_index(drop=True).to_list()
j24Bsls.loc[j24Bsls.location_id.isin(j24UnderservedIds), 'status'] = 'Underserved'
j24ServedIds = j24[(j24.max_advertised_download_speed >= 100) & (j24.max_advertised_upload_speed >= 20) & (j24.technology.isin(tech))] \
  .location_id.drop_duplicates() \
  .reset_index(drop=True).to_list()
j24Bsls.loc[j24Bsls.location_id.isin(j24ServedIds), 'status'] = 'Served'

In [ ]:
j24Bsls.status.value_counts()

In [ ]:
print(f'D22 Not Served BSLs: {176252+122295:,}')
print(f'J24 Not Served BSLs: {144526+97871:,}')

## Correlational Analysis

## M-Lab Data (NDT)

In [ ]:
guide = NDTGuide()
guide.login()

In [ ]:
# sql = guide.sql_get_clients(table_name='ndt7', date_start='2025-08-01', date_end='2025-08-31', aggr_func='avg', client_country='us')
sql = guide.sql_get_clients('ndt7', '2025-08-01', '2025-08-31', 'avg', client_country='us')

In [ ]:
sql = guide.sql_daily_aggregate("ndt7", "2022-09-01", "2025-09-10", "avg", client_country="us")
guide.exec_sql(sql)

In [ ]:
guide.exec_sql(sql)

## OOKLA

In [ ]:
!aws s3 cp --no-sign-request s3://ookla-open-data/parquet/performance/type=fixed/year=2025/quarter=2/2025-04-01_performance_fixed_tiles.parquet ./

In [ ]:
ookla = pd.read_parquet('2025-04-01_performance_fixed_tiles.parquet')

In [ ]:
ookla

In [ ]:
from shapely import wkt

# Convert the 'tile' column from WKT strings to geometry objects
geometry = ookla['tile'].apply(wkt.loads)

# Create a GeoDataFrame using the converted geometry and the original DataFrame
ookla_gdf = gpd.GeoDataFrame(ookla, geometry=geometry)

In [ ]:
ookla_gdf.sample(n=10)

In [ ]:
fig, ax2 = plt.subplots(figsize=(16, 16))
waOokla_gdf.plot(ax=ax2, column='avg_d_kbps', scheme='FisherJenks', legend=True)

In [ ]:
fig.close()