<a href="https://colab.research.google.com/github/npappin-wsu/BroadbandDataQuickstart/blob/main/J25_Broadband_report.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Broadband Market Summary

## Data retrieval

In [ ]:
!git clone https://github.com/npappin-wsu/j25BroadbandReport.git data
!git -C data pull
!pip install -r data/requirements.txt

Requirement already satisfied: bdcdata in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 1)) (0.0.10)
Requirement already satisfied: h3pandas in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 2)) (0.3.0)
Requirement already satisfied: folium in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 3)) (0.20.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 4)) (3.10.0)
Requirement already satisfied: mapclassify in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 5)) (2.10.0)
Requirement already satisfied: pygris in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 6)) (0.2.1)
Requirement already satisfied: pandas>=2 in /usr/local/lib/python3.12/dist-packages (from bdcdata->-r requirements.txt (line 1)) (2.2.2)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (from bdcdata->-r requirements.txt (line 1)) (18.1.0)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (from bdcdata->-r requirements.txt (line 1)) (1.2.1)
Requirement already satisfied: requests-ratelimiter in /usr/local/lib/python3.12/dist-packages (from bdcdata->-r requirements.txt (line 1)) (0.8.0)
Requirement already satisfied: geopandas in /usr/local/lib/python3.12/dist-packages (from h3pandas->-r requirements.txt (line 2)) (1.1.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from h3pandas->-r requirements.txt (line 2)) (2.0.2)
Requirement already satisfied: shapely in /usr/local/lib/python3.12/dist-packages (from h3pandas->-r requirements.txt (line 2)) (2.1.2)
Requirement already satisfied: h3>=4 in /usr/local/lib/python3.12/dist-packages (from h3pandas->-r requirements.txt (line 2)) (4.4.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from h3pandas->-r requirements.txt (line 2)) (4.15.0)
Requirement already satisfied: branca>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from folium->-r requirements.txt (line 3)) (0.8.2)
Requirement already satisfied: jinja2>=2.9 in /usr/local/lib/python3.12/dist-packages (from folium->-r requirements.txt (line 3)) (3.1.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from folium->-r requirements.txt (line 3)) (2.32.4)
Requirement already satisfied: xyzservices in /usr/local/lib/python3.12/dist-packages (from folium->-r requirements.txt (line 3)) (2025.11.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 4)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 4)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 4)) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 4)) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 4)) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 4)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 4)) (3.3.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 4)) (2.9.0.post0)
Requirement already satisfied: networkx>=3.2 in /usr/local/lib/python3.12/dist-packages (from mapclassify->-r requirements.txt (line 5)) (3.6.1)
Requirement already satisfied: scikit-learn>=1.4 in /usr/local/lib/python3.12/dist-packages (from mapclassify->-r requirements.txt (line 5)) (1.6.1)
Requirement already satisfied: scipy>=1.12 in /usr/local/lib/python3.12/dist-packages (from mapclassify->-r requirements.txt (line 5)) (1.16.3)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from pygris->-r requirements.txt (line 6)) (4.5.1)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.12/dist-packages (from geopandas->h3pandas->-r requirements.txt (line 2)) (0.12.1)
Requirement already satisfied: pyproj>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from geopandas->h3pandas->-r requirements.txt (line 2)) (3.7.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.9->folium->-r requirements.txt (line 3)) (3.0.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2->bdcdata->-r requirements.txt (line 1)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2->bdcdata->-r requirements.txt (line 1)) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->-r requirements.txt (line 4)) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4->mapclassify->-r requirements.txt (line 5)) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4->mapclassify->-r requirements.txt (line 5)) (3.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->folium->-r requirements.txt (line 3)) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->folium->-r requirements.txt (line 3)) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->folium->-r requirements.txt (line 3)) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->folium->-r requirements.txt (line 3)) (2026.1.4)
Requirement already satisfied: pyrate-limiter<3.0 in /usr/local/lib/python3.12/dist-packages (from requests-ratelimiter->bdcdata->-r requirements.txt (line 1)) (2.10.0)

In [ ]:
import os, pathlib, h3pandas, pygris, datetime
from google.colab import userdata
import pandas as pd
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt
os.environ["BDC_USERNAME"] = userdata.get('bdc_email')
os.environ["BDC_API_KEY"] = userdata.get('bdc_hash')

In [ ]:
import bdcdata

{'User-Agent': 'python-bdc', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'hash_value': 'bfhH+tiaOBFlIX9SBrMoscNBurVioE6YMkfCPSjf4V4=', 'username': 'nick.pappin@wsu.edu'}
DEBUG:bdcdata:{'User-Agent': 'python-bdc', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'hash_value': 'bfhH+tiaOBFlIX9SBrMoscNBurVioE6YMkfCPSjf4V4=', 'username': 'nick.pappin@wsu.edu'}
Session created.
INFO:bdcdata:Session created.
Collecting metadata...
INFO:bdcdata:Collecting metadata...
{'data': [{'data_type': 'availability', 'as_of_date': '2022-06-30'}, {'data_type': 'availability', 'as_of_date': '2022-12-31'}, {'data_type': 'availability', 'as_of_date': '2023-06-30'}, {'data_type': 'availability', 'as_of_date': '2023-12-31'}, {'data_type': 'availability', 'as_of_date': '2024-06-30'}, {'data_type': 'availability', 'as_of_date': '2024-12-31'}, {'data_type': 'availability', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2022-11-30'}, {'data_type': 'challenge', 'as_of_date': '2022-12-31'}, {'data_type': 'challenge', 'as_of_date': '2023-01-31'}, {'data_type': 'challenge', 'as_of_date': '2023-02-28'}, {'data_type': 'challenge', 'as_of_date': '2023-03-31'}, {'data_type': 'challenge', 'as_of_date': '2023-04-30'}, {'data_type': 'challenge', 'as_of_date': '2023-05-31'}, {'data_type': 'challenge', 'as_of_date': '2023-06-30'}, {'data_type': 'challenge', 'as_of_date': '2023-07-31'}, {'data_type': 'challenge', 'as_of_date': '2023-08-31'}, {'data_type': 'challenge', 'as_of_date': '2023-09-30'}, {'data_type': 'challenge', 'as_of_date': '2023-10-31'}, {'data_type': 'challenge', 'as_of_date': '2023-11-30'}, {'data_type': 'challenge', 'as_of_date': '2023-12-31'}, {'data_type': 'challenge', 'as_of_date': '2024-01-31'}, {'data_type': 'challenge', 'as_of_date': '2024-02-29'}, {'data_type': 'challenge', 'as_of_date': '2024-03-31'}, {'data_type': 'challenge', 'as_of_date': '2024-04-30'}, {'data_type': 'challenge', 'as_of_date': '2024-05-31'}, {'data_type': 'challenge', 'as_of_date': '2024-06-30'}, {'data_type': 'challenge', 'as_of_date': '2024-07-31'}, {'data_type': 'challenge', 'as_of_date': '2024-08-31'}, {'data_type': 'challenge', 'as_of_date': '2024-09-30'}, {'data_type': 'challenge', 'as_of_date': '2024-10-31'}, {'data_type': 'challenge', 'as_of_date': '2024-11-30'}, {'data_type': 'challenge', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2025-01-31'}, {'data_type': 'challenge', 'as_of_date': '2025-02-28'}, {'data_type': 'challenge', 'as_of_date': '2025-03-31'}, {'data_type': 'challenge', 'as_of_date': '2025-04-30'}, {'data_type': 'challenge', 'as_of_date': '2025-05-31'}, {'data_type': 'challenge', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2025-07-31'}, {'data_type': 'challenge', 'as_of_date': '2025-08-31'}, {'data_type': 'challenge', 'as_of_date': '2025-09-30'}, {'data_type': 'challenge', 'as_of_date': '2025-10-31'}, {'data_type': 'challenge', 'as_of_date': '2025-11-30'}, {'data_type': 'challenge', 'as_of_date': '2025-12-31'}], 'result_count': 45, 'status_code': 200, 'message': None, 'status': 'successful', 'request_date': '2026-01-14T20:11:35.582Z'}
DEBUG:bdcdata:{'data': [{'data_type': 'availability', 'as_of_date': '2022-06-30'}, {'data_type': 'availability', 'as_of_date': '2022-12-31'}, {'data_type': 'availability', 'as_of_date': '2023-06-30'}, {'data_type': 'availability', 'as_of_date': '2023-12-31'}, {'data_type': 'availability', 'as_of_date': '2024-06-30'}, {'data_type': 'availability', 'as_of_date': '2024-12-31'}, {'data_type': 'availability', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2022-11-30'}, {'data_type': 'challenge', 'as_of_date': '2022-12-31'}, {'data_type': 'challenge', 'as_of_date': '2023-01-31'}, {'data_type': 'challenge', 'as_of_date': '2023-02-28'}, {'data_type': 'challenge', 'as_of_date': '2023-03-31'}, {'data_type': 'challenge', 'as_of_date': '2023-04-30'}, {'data_type': 'challenge', 'as_of_date': '2023-05-31'}, {'data_type': 'challenge', 'as_of_date': '2023-06-30'}, {'data_type': 'challenge', 'as_of_date': '2023-07-31'}, {'data_type': 'challenge', 'as_of_date': '2023-08-31'}, {'data_type': 'challenge', 'as_of_date': '2023-09-30'}, {'data_type': 'challenge', 'as_of_date': '2023-10-31'}, {'data_type': 'challenge', 'as_of_date': '2023-11-30'}, {'data_type': 'challenge', 'as_of_date': '2023-12-31'}, {'data_type': 'challenge', 'as_of_date': '2024-01-31'}, {'data_type': 'challenge', 'as_of_date': '2024-02-29'}, {'data_type': 'challenge', 'as_of_date': '2024-03-31'}, {'data_type': 'challenge', 'as_of_date': '2024-04-30'}, {'data_type': 'challenge', 'as_of_date': '2024-05-31'}, {'data_type': 'challenge', 'as_of_date': '2024-06-30'}, {'data_type': 'challenge', 'as_of_date': '2024-07-31'}, {'data_type': 'challenge', 'as_of_date': '2024-08-31'}, {'data_type': 'challenge', 'as_of_date': '2024-09-30'}, {'data_type': 'challenge', 'as_of_date': '2024-10-31'}, {'data_type': 'challenge', 'as_of_date': '2024-11-30'}, {'data_type': 'challenge', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2025-01-31'}, {'data_type': 'challenge', 'as_of_date': '2025-02-28'}, {'data_type': 'challenge', 'as_of_date': '2025-03-31'}, {'data_type': 'challenge', 'as_of_date': '2025-04-30'}, {'data_type': 'challenge', 'as_of_date': '2025-05-31'}, {'data_type': 'challenge', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2025-07-31'}, {'data_type': 'challenge', 'as_of_date': '2025-08-31'}, {'data_type': 'challenge', 'as_of_date': '2025-09-30'}, {'data_type': 'challenge', 'as_of_date': '2025-10-31'}, {'data_type': 'challenge', 'as_of_date': '2025-11-30'}, {'data_type': 'challenge', 'as_of_date': '2025-12-31'}], 'result_count': 45, 'status_code': 200, 'message': None, 'status': 'successful', 'request_date': '2026-01-14T20:11:35.582Z'}
{'data': [{'data_type': 'availability', 'as_of_date': '2022-06-30'}, {'data_type': 'availability', 'as_of_date': '2022-12-31'}, {'data_type': 'availability', 'as_of_date': '2023-06-30'}, {'data_type': 'availability', 'as_of_date': '2023-12-31'}, {'data_type': 'availability', 'as_of_date': '2024-06-30'}, {'data_type': 'availability', 'as_of_date': '2024-12-31'}, {'data_type': 'availability', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2022-11-30'}, {'data_type': 'challenge', 'as_of_date': '2022-12-31'}, {'data_type': 'challenge', 'as_of_date': '2023-01-31'}, {'data_type': 'challenge', 'as_of_date': '2023-02-28'}, {'data_type': 'challenge', 'as_of_date': '2023-03-31'}, {'data_type': 'challenge', 'as_of_date': '2023-04-30'}, {'data_type': 'challenge', 'as_of_date': '2023-05-31'}, {'data_type': 'challenge', 'as_of_date': '2023-06-30'}, {'data_type': 'challenge', 'as_of_date': '2023-07-31'}, {'data_type': 'challenge', 'as_of_date': '2023-08-31'}, {'data_type': 'challenge', 'as_of_date': '2023-09-30'}, {'data_type': 'challenge', 'as_of_date': '2023-10-31'}, {'data_type': 'challenge', 'as_of_date': '2023-11-30'}, {'data_type': 'challenge', 'as_of_date': '2023-12-31'}, {'data_type': 'challenge', 'as_of_date': '2024-01-31'}, {'data_type': 'challenge', 'as_of_date': '2024-02-29'}, {'data_type': 'challenge', 'as_of_date': '2024-03-31'}, {'data_type': 'challenge', 'as_of_date': '2024-04-30'}, {'data_type': 'challenge', 'as_of_date': '2024-05-31'}, {'data_type': 'challenge', 'as_of_date': '2024-06-30'}, {'data_type': 'challenge', 'as_of_date': '2024-07-31'}, {'data_type': 'challenge', 'as_of_date': '2024-08-31'}, {'data_type': 'challenge', 'as_of_date': '2024-09-30'}, {'data_type': 'challenge', 'as_of_date': '2024-10-31'}, {'data_type': 'challenge', 'as_of_date': '2024-11-30'}, {'data_type': 'challenge', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2025-01-31'}, {'data_type': 'challenge', 'as_of_date': '2025-02-28'}, {'data_type': 'challenge', 'as_of_date': '2025-03-31'}, {'data_type': 'challenge', 'as_of_date': '2025-04-30'}, {'data_type': 'challenge', 'as_of_date': '2025-05-31'}, {'data_type': 'challenge', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2025-07-31'}, {'data_type': 'challenge', 'as_of_date': '2025-08-31'}, {'data_type': 'challenge', 'as_of_date': '2025-09-30'}, {'data_type': 'challenge', 'as_of_date': '2025-10-31'}, {'data_type': 'challenge', 'as_of_date': '2025-11-30'}, {'data_type': 'challenge', 'as_of_date': '2025-12-31'}], 'result_count': 45, 'status_code': 200, 'message': None, 'status': 'successful', 'request_date': '2026-01-14T20:11:35.582Z'}
INFO:bdcdata:{'data': [{'data_type': 'availability', 'as_of_date': '2022-06-30'}, {'data_type': 'availability', 'as_of_date': '2022-12-31'}, {'data_type': 'availability', 'as_of_date': '2023-06-30'}, {'data_type': 'availability', 'as_of_date': '2023-12-31'}, {'data_type': 'availability', 'as_of_date': '2024-06-30'}, {'data_type': 'availability', 'as_of_date': '2024-12-31'}, {'data_type': 'availability', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2022-11-30'}, {'data_type': 'challenge', 'as_of_date': '2022-12-31'}, {'data_type': 'challenge', 'as_of_date': '2023-01-31'}, {'data_type': 'challenge', 'as_of_date': '2023-02-28'}, {'data_type': 'challenge', 'as_of_date': '2023-03-31'}, {'data_type': 'challenge', 'as_of_date': '2023-04-30'}, {'data_type': 'challenge', 'as_of_date': '2023-05-31'}, {'data_type': 'challenge', 'as_of_date': '2023-06-30'}, {'data_type': 'challenge', 'as_of_date': '2023-07-31'}, {'data_type': 'challenge', 'as_of_date': '2023-08-31'}, {'data_type': 'challenge', 'as_of_date': '2023-09-30'}, {'data_type': 'challenge', 'as_of_date': '2023-10-31'}, {'data_type': 'challenge', 'as_of_date': '2023-11-30'}, {'data_type': 'challenge', 'as_of_date': '2023-12-31'}, {'data_type': 'challenge', 'as_of_date': '2024-01-31'}, {'data_type': 'challenge', 'as_of_date': '2024-02-29'}, {'data_type': 'challenge', 'as_of_date': '2024-03-31'}, {'data_type': 'challenge', 'as_of_date': '2024-04-30'}, {'data_type': 'challenge', 'as_of_date': '2024-05-31'}, {'data_type': 'challenge', 'as_of_date': '2024-06-30'}, {'data_type': 'challenge', 'as_of_date': '2024-07-31'}, {'data_type': 'challenge', 'as_of_date': '2024-08-31'}, {'data_type': 'challenge', 'as_of_date': '2024-09-30'}, {'data_type': 'challenge', 'as_of_date': '2024-10-31'}, {'data_type': 'challenge', 'as_of_date': '2024-11-30'}, {'data_type': 'challenge', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2025-01-31'}, {'data_type': 'challenge', 'as_of_date': '2025-02-28'}, {'data_type': 'challenge', 'as_of_date': '2025-03-31'}, {'data_type': 'challenge', 'as_of_date': '2025-04-30'}, {'data_type': 'challenge', 'as_of_date': '2025-05-31'}, {'data_type': 'challenge', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2025-07-31'}, {'data_type': 'challenge', 'as_of_date': '2025-08-31'}, {'data_type': 'challenge', 'as_of_date': '2025-09-30'}, {'data_type': 'challenge', 'as_of_date': '2025-10-31'}, {'data_type': 'challenge', 'as_of_date': '2025-11-30'}, {'data_type': 'challenge', 'as_of_date': '2025-12-31'}], 'result_count': 45, 'status_code': 200, 'message': None, 'status': 'successful', 'request_date': '2026-01-14T20:11:35.582Z'}
[{'data_type': 'availability', 'as_of_date': '2022-06-30'}, {'data_type': 'availability', 'as_of_date': '2022-12-31'}, {'data_type': 'availability', 'as_of_date': '2023-06-30'}, {'data_type': 'availability', 'as_of_date': '2023-12-31'}, {'data_type': 'availability', 'as_of_date': '2024-06-30'}, {'data_type': 'availability', 'as_of_date': '2024-12-31'}, {'data_type': 'availability', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2022-11-30'}, {'data_type': 'challenge', 'as_of_date': '2022-12-31'}, {'data_type': 'challenge', 'as_of_date': '2023-01-31'}, {'data_type': 'challenge', 'as_of_date': '2023-02-28'}, {'data_type': 'challenge', 'as_of_date': '2023-03-31'}, {'data_type': 'challenge', 'as_of_date': '2023-04-30'}, {'data_type': 'challenge', 'as_of_date': '2023-05-31'}, {'data_type': 'challenge', 'as_of_date': '2023-06-30'}, {'data_type': 'challenge', 'as_of_date': '2023-07-31'}, {'data_type': 'challenge', 'as_of_date': '2023-08-31'}, {'data_type': 'challenge', 'as_of_date': '2023-09-30'}, {'data_type': 'challenge', 'as_of_date': '2023-10-31'}, {'data_type': 'challenge', 'as_of_date': '2023-11-30'}, {'data_type': 'challenge', 'as_of_date': '2023-12-31'}, {'data_type': 'challenge', 'as_of_date': '2024-01-31'}, {'data_type': 'challenge', 'as_of_date': '2024-02-29'}, {'data_type': 'challenge', 'as_of_date': '2024-03-31'}, {'data_type': 'challenge', 'as_of_date': '2024-04-30'}, {'data_type': 'challenge', 'as_of_date': '2024-05-31'}, {'data_type': 'challenge', 'as_of_date': '2024-06-30'}, {'data_type': 'challenge', 'as_of_date': '2024-07-31'}, {'data_type': 'challenge', 'as_of_date': '2024-08-31'}, {'data_type': 'challenge', 'as_of_date': '2024-09-30'}, {'data_type': 'challenge', 'as_of_date': '2024-10-31'}, {'data_type': 'challenge', 'as_of_date': '2024-11-30'}, {'data_type': 'challenge', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2025-01-31'}, {'data_type': 'challenge', 'as_of_date': '2025-02-28'}, {'data_type': 'challenge', 'as_of_date': '2025-03-31'}, {'data_type': 'challenge', 'as_of_date': '2025-04-30'}, {'data_type': 'challenge', 'as_of_date': '2025-05-31'}, {'data_type': 'challenge', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2025-07-31'}, {'data_type': 'challenge', 'as_of_date': '2025-08-31'}, {'data_type': 'challenge', 'as_of_date': '2025-09-30'}, {'data_type': 'challenge', 'as_of_date': '2025-10-31'}, {'data_type': 'challenge', 'as_of_date': '2025-11-30'}, {'data_type': 'challenge', 'as_of_date': '2025-12-31'}]
DEBUG:bdcdata:[{'data_type': 'availability', 'as_of_date': '2022-06-30'}, {'data_type': 'availability', 'as_of_date': '2022-12-31'}, {'data_type': 'availability', 'as_of_date': '2023-06-30'}, {'data_type': 'availability', 'as_of_date': '2023-12-31'}, {'data_type': 'availability', 'as_of_date': '2024-06-30'}, {'data_type': 'availability', 'as_of_date': '2024-12-31'}, {'data_type': 'availability', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2022-11-30'}, {'data_type': 'challenge', 'as_of_date': '2022-12-31'}, {'data_type': 'challenge', 'as_of_date': '2023-01-31'}, {'data_type': 'challenge', 'as_of_date': '2023-02-28'}, {'data_type': 'challenge', 'as_of_date': '2023-03-31'}, {'data_type': 'challenge', 'as_of_date': '2023-04-30'}, {'data_type': 'challenge', 'as_of_date': '2023-05-31'}, {'data_type': 'challenge', 'as_of_date': '2023-06-30'}, {'data_type': 'challenge', 'as_of_date': '2023-07-31'}, {'data_type': 'challenge', 'as_of_date': '2023-08-31'}, {'data_type': 'challenge', 'as_of_date': '2023-09-30'}, {'data_type': 'challenge', 'as_of_date': '2023-10-31'}, {'data_type': 'challenge', 'as_of_date': '2023-11-30'}, {'data_type': 'challenge', 'as_of_date': '2023-12-31'}, {'data_type': 'challenge', 'as_of_date': '2024-01-31'}, {'data_type': 'challenge', 'as_of_date': '2024-02-29'}, {'data_type': 'challenge', 'as_of_date': '2024-03-31'}, {'data_type': 'challenge', 'as_of_date': '2024-04-30'}, {'data_type': 'challenge', 'as_of_date': '2024-05-31'}, {'data_type': 'challenge', 'as_of_date': '2024-06-30'}, {'data_type': 'challenge', 'as_of_date': '2024-07-31'}, {'data_type': 'challenge', 'as_of_date': '2024-08-31'}, {'data_type': 'challenge', 'as_of_date': '2024-09-30'}, {'data_type': 'challenge', 'as_of_date': '2024-10-31'}, {'data_type': 'challenge', 'as_of_date': '2024-11-30'}, {'data_type': 'challenge', 'as_of_date': '2024-12-31'}, {'data_type': 'challenge', 'as_of_date': '2025-01-31'}, {'data_type': 'challenge', 'as_of_date': '2025-02-28'}, {'data_type': 'challenge', 'as_of_date': '2025-03-31'}, {'data_type': 'challenge', 'as_of_date': '2025-04-30'}, {'data_type': 'challenge', 'as_of_date': '2025-05-31'}, {'data_type': 'challenge', 'as_of_date': '2025-06-30'}, {'data_type': 'challenge', 'as_of_date': '2025-07-31'}, {'data_type': 'challenge', 'as_of_date': '2025-08-31'}, {'data_type': 'challenge', 'as_of_date': '2025-09-30'}, {'data_type': 'challenge', 'as_of_date': '2025-10-31'}, {'data_type': 'challenge', 'as_of_date': '2025-11-30'}, {'data_type': 'challenge', 'as_of_date': '2025-12-31'}]
Metadata collected.
INFO:bdcdata:Metadata collected.
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2022-11-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2022-11-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2022-12-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2022-12-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-01-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-01-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-02-28'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-02-28'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-03-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-03-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-04-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-04-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-05-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-05-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-06-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-06-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-07-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-07-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-08-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-08-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-09-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-09-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-10-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-10-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-11-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-11-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2023-12-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2023-12-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-01-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-01-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-02-29'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-02-29'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-03-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-03-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-04-30'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-04-30'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-05-31'}
DEBUG:bdcdata:{'data_type': 'challenge', 'as_of_date': '2024-05-31'}
Data type: challenge
DEBUG:bdcdata:Data type: challenge
{'data_type': 'challenge', 'as_of_date': '2024-06-30'}

In [ ]:
release = datetime.datetime(2026, 6, 30)

2026-06-30

In [ ]:
waAvailability = bdcdata.availability.fixed(states=[53], technology='fixed', release=[release.strftime('%Y-%m-%d')], cache=True)

Collecting availability...
INFO:bdcdata:Collecting availability...
State: [53]
DEBUG:bdcdata:State: [53]
Technology: fixed
DEBUG:bdcdata:Technology: fixed
Release: ['2025-06-30']
DEBUG:bdcdata:Release: ['2025-06-30']
State: Washington({'file_id': 1403681, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '10', 'technology_code_desc': 'Copper', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_Copper_fixed_broadband_J25_06jan2026', 'record_count': '1083523'})), Technology: 10, Release: 2025-06-30
DEBUG:bdcdata:State: Washington({'file_id': 1403681, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '10', 'technology_code_desc': 'Copper', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_Copper_fixed_broadband_J25_06jan2026', 'record_count': '1083523'})), Technology: 10, Release: 2025-06-30
State: Washington({'file_id': 1403735, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '40', 'technology_code_desc': 'Cable', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_Cable_fixed_broadband_J25_06jan2026', 'record_count': '2288433'})), Technology: 40, Release: 2025-06-30
DEBUG:bdcdata:State: Washington({'file_id': 1403735, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '40', 'technology_code_desc': 'Cable', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_Cable_fixed_broadband_J25_06jan2026', 'record_count': '2288433'})), Technology: 40, Release: 2025-06-30
State: Washington({'file_id': 1403791, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '50', 'technology_code_desc': 'Fiber to the Premises', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_FibertothePremises_fixed_broadband_J25_06jan2026', 'record_count': '1100140'})), Technology: 50, Release: 2025-06-30
DEBUG:bdcdata:State: Washington({'file_id': 1403791, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '50', 'technology_code_desc': 'Fiber to the Premises', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_FibertothePremises_fixed_broadband_J25_06jan2026', 'record_count': '1100140'})), Technology: 50, Release: 2025-06-30
State: Washington({'file_id': 1403847, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '60', 'technology_code_desc': 'GSO Satellite', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_GSOSatellite_fixed_broadband_J25_06jan2026', 'record_count': '7701683'})), Technology: 60, Release: 2025-06-30
DEBUG:bdcdata:State: Washington({'file_id': 1403847, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '60', 'technology_code_desc': 'GSO Satellite', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_GSOSatellite_fixed_broadband_J25_06jan2026', 'record_count': '7701683'})), Technology: 60, Release: 2025-06-30
State: Washington({'file_id': 1403900, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '61', 'technology_code_desc': 'NGSO Satellite', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_NGSOSatellite_fixed_broadband_J25_06jan2026', 'record_count': '2563700'})), Technology: 61, Release: 2025-06-30
DEBUG:bdcdata:State: Washington({'file_id': 1403900, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '61', 'technology_code_desc': 'NGSO Satellite', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_NGSOSatellite_fixed_broadband_J25_06jan2026', 'record_count': '2563700'})), Technology: 61, Release: 2025-06-30
State: Washington({'file_id': 1403956, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '70', 'technology_code_desc': 'Unlicensed Fixed Wireless', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_UnlicensedFixedWireless_fixed_broadband_J25_06jan2026', 'record_count': '1118752'})), Technology: 70, Release: 2025-06-30
DEBUG:bdcdata:State: Washington({'file_id': 1403956, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '70', 'technology_code_desc': 'Unlicensed Fixed Wireless', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_UnlicensedFixedWireless_fixed_broadband_J25_06jan2026', 'record_count': '1118752'})), Technology: 70, Release: 2025-06-30
State: Washington({'file_id': 1404011, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '71', 'technology_code_desc': 'Licensed Fixed Wireless', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_LicensedFixedWireless_fixed_broadband_J25_06jan2026', 'record_count': '4528475'})), Technology: 71, Release: 2025-06-30
DEBUG:bdcdata:State: Washington({'file_id': 1404011, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '71', 'technology_code_desc': 'Licensed Fixed Wireless', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_LicensedFixedWireless_fixed_broadband_J25_06jan2026', 'record_count': '4528475'})), Technology: 71, Release: 2025-06-30
State: Washington({'file_id': 1404060, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '72', 'technology_code_desc': 'LBR Fixed Wireless', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_LBRFixedWireless_fixed_broadband_J25_06jan2026', 'record_count': '221076'})), Technology: 72, Release: 2025-06-30
DEBUG:bdcdata:State: Washington({'file_id': 1404060, 'category': 'State', 'subcategory': 'Location Coverage', 'technology_type': 'Fixed Broadband', 'technology_code': '72', 'technology_code_desc': 'LBR Fixed Wireless', 'speed_tier': None, 'state_fips': '53', 'state_name': 'Washington', 'provider_id': None, 'provider_name': None, 'file_type': 'csv', 'file_name': 'bdc_53_LBRFixedWireless_fixed_broadband_J25_06jan2026', 'record_count': '221076'})), Technology: 72, Release: 2025-06-30
State: ['53'], Technology: ['0', '10', '40', '50', '60', '61', '70', '71', '72'], Release: ['2025-06-30']
DEBUG:bdcdata:State: ['53'], Technology: ['0', '10', '40', '50', '60', '61', '70', '71', '72'], Release: ['2025-06-30']

In [ ]:
# @title
first = next(pathlib.Path('cache').iterdir())
intraReleaseDate = datetime.datetime.strptime(str(first)[-13:-4], '%d%b%Y')
string = f"""This analysis will use data from {intraReleaseDate.strftime('%A, %B, %d %Y')} of the {release.strftime('%B %Y')} BDC Availability dataset.
"""
print(string)

This analysis will use data from Tuesday, January, 06 2026 of the June 2026 BDC Availability dataset.

In [ ]:
#add code here to make the dataframe friendlier.
#change technology into name
#change long field names
waAvailability.rename({"max_advertised_download_speed": "max_down", "max_advertised_upload_speed": "max_up"})

,frn,provider_id,brand_name,location_id,technology,max_advertised_download_speed,max_advertised_upload_speed,low_latency,business_residential_code,state_usps,block_geoid,h3_res8_id,release
0,0018582510,190303,Douglas County P.U.D.,1121308022,10,1000,1000,True,X,WA,530179504004020,8828d681a1fffff,2025-06-30
1,0018582510,190303,Douglas County P.U.D.,1121309093,10,1000,1000,True,X,WA,530179503003009,8828d68133fffff,2025-06-30
2,0018582510,190303,Douglas County P.U.D.,1121313485,10,1000,1000,True,X,WA,530179508002009,8828d6811bfffff,2025-06-30
3,0018582510,190303,Douglas County P.U.D.,1121318023,10,1000,1000,True,X,WA,530179508003045,8828d68025fffff,2025-06-30
4,0018582510,190303,Douglas County P.U.D.,1121319492,10,1000,1000,True,X,WA,530179505002001,8828d68189fffff,2025-06-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20605777,0031764293,420173,Ziply Wireless,1342712264,72,25,5,True,X,WA,530630102011020,8812db0749fffff,2025-06-30
20605778,0031764293,420173,Ziply Wireless,1342746597,72,50,10,True,X,WA,530630112024002,8812db0cdbfffff,2025-06-30
20605779,0031764293,420173,Ziply Wireless,1410095373,72,50,10,True,X,WA,530250105001029,88288968bdfffff,2025-06-30
20605780,0031764293,420173,Ziply Wireless,1414827113,72,50,10,True,X,WA,530079608041010,8828d68e4dfffff,2025-06-30
20605781,0031764293,420173,Ziply Wireless,1564174977,72,50,10,True,X,WA,530079603021002,8828d6081bfffff,2025-06-30

In [51]:
waAvailability.location_id.drop_duplicates().shape

0           1121308022
1           1121309093
2           1121313485
3           1121318023
4           1121319492
               ...
12172200    1605519558
12172201    1605519565
12172202    1605520090
12172203    1605520959
14321353    1349409498
Name: location_id, Length: 2564349, dtype: UInt32

##Top ISPs in Washington

In [50]:
waAvailability[["location_id", "brand_name"]].drop_duplicates()

          location_id             brand_name
0          1121308022  Douglas County P.U.D.
1          1121309093  Douglas County P.U.D.
2          1121313485  Douglas County P.U.D.
3          1121318023  Douglas County P.U.D.
4          1121319492  Douglas County P.U.D.
...               ...                    ...
20605777   1342712264         Ziply Wireless
20605778   1342746597         Ziply Wireless
20605779   1410095373         Ziply Wireless
20605780   1414827113         Ziply Wireless
20605781   1564174977         Ziply Wireless

[20605782 rows x 2 columns]